### ISSUE TITLE
[meson] support custom target "symstall (install_symlink)"

### ISSUE THREAD

**Issue by MaskRay** [radareorg/radare2#10930]
The `Makefile`s r2 uses have a target `symstall` which installs symlinks in `$PREFIX`. It'll be useful to have a counterpart in the meson build system. There are some requests for implementing the feature in meson upstream but no progress has been made yet https://github.com/mesonbuild/meson/issues/1602

I currently use these commands:
```zsh
CC=~/llvm/Stable/bin/clang CXX=~/llvm/Stable/bin/clang++ LDFLAGS=-fuse-ld=lld meson . release --buildtype=release --prefix ~/.config/radare2/release
ninja -C release # frequently used
ninja -C release install # from time to time when */d files get stale

cd ~/.local/share/radare2
ln -s ~/Dev/Bin/radare2/libr/cons/d cons
ln -s ~/Dev/Bin/radare2/release/libr/anal/d anal
ln -s ~/Dev/Bin/radare2/release/libr/asm/d asm
ln -s ~/Dev/Bin/radare2/release/libr/bin/d bin
ln -s ~/Dev/Bin/radare2/release/libr/flag/d flag
ln -s ~/Dev/Bin/radare2/release/libr/syscall/d syscall
```

Detailed setup at https://github.com/MaskRay/Config/wiki#radare2

**Comment by Maijin** [comment]
@ret2libc

**Comment by ret2libc** [comment]
Why do you need symstall with meson? What benefit would it brings?
I think the reason symlinks were introduced in Makefile is that you have to install radare2 to make it work correctly and it is easier when developing to just compile and then have that installed.

With meson though I don't have that requirement, personally. I just compile in the `build` directory and I can test the compiled `radare` directly from the build directory. I don't need to install it just because I'm developing. Moreover, it makes it sooo easier to test different commits/branches/etc. because you just need to compile radare in different build directories.

**Comment by MaskRay** [comment]
My preference from top to bottom:

* Using the executable in the build directory. This does not always work. If this could work without making symlinks as I do `ln -s ~/Dev/Bin/radare2/release/libr/asm/d asm`, I agree `symstall` is not necessary.
* symstall'ed executable
* installed executable
* `/usr/bin/r2` `/usr/local/bin/r2`

**Comment by ret2libc** [comment]
Ok those directories are probably somehow hardcoded in the code. We should maybe provide a way to use them relative to the executable path or something like that.

Anyway, as you noticed meson is not very friendly at the moment with links :( (we don't even symlink radare2 to r2). And I honestly don't like having symlinks in my system. I prefer to just install, as I do with any other software.

**Comment by ret2libc** [comment]
I think this is something that neither autotools can fix by default. Meson uses rpath to find libraries, but files in `/usr/share/radare2/2.8.0/{cons,flag,syscall,etc.}` are referenced by hard coded paths, so we can address this by also trying to locate those files in relative dirs first.

**Comment by ret2libc** [comment]
I think I'm going to close this as wontfix. I still don't see the benefit of having symlinks instead of real files installed on your systems. I use almost always radare2 from within the build directory, unless there have been some changes in the installed files in `share/radare2/{cons,flag,syscalls,etc.}`, in which case I do `ninja -C build install`.

files in `libr/asm/d`, `libr/anal/d`, etc. are installed with `ninja -C build install` and once that's done you can just run radare2 from the build directory. If what we want is to have those files referenced as relative dirs, that's not a meson-specifc issue and in that case let's open a bug for that. Because if that's the case, also a `./configure;make` radare2 won't work.
