### ISSUE TITLE
Remove `bool RList::sorted`

### ISSUE THREAD

**Issue by MaskRay** [radareorg/radare2#10945]
The field has very less to do with a list, has very few uses, and is hard for bookkeeping.

![](https://ptpb.pw/a8Sq.jpg)

**Comment by radare** [comment]
its very useful to avoid sorting it twice, which basically makes many things faster. i would keep it, because adding over9000 wrappers of all the data structures we have for just having some meta attributes makes the code harder to maintain.

**Comment by radare** [comment]
this sorted thing have been anoying me a bit in here :{ https://github.com/radare/radare2/pull/13593 mainly because i was sorting using a different method. maybe we can use void* in ssorted and hold the sorting function as value and use NULL for unsorted. this way we avoid resorting twice with the same algorithm. but i think @MaskRay is right here and we should move this memoization outside the RList struct.

comments on this @ret2libc ? we should check the uses of r_list_sort, and this is probably causing some bugs we dont even know about.

**Comment by ret2libc** [comment]
Let's close this. I don't think there is any need to keep this issue open. Someone will refactor this if/when needed, I guess. WDYT @radare ?
