### ISSUE TITLE
Regression in m68k analysis

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#11056]
After the recent update of capstone (usage of master). The analysis of m68k branch got broken again:
https://github.com/radare/radare2/commit/adc9922c6aceacc0cffa89bc45a20250a5e43e1f

Binary:
[METRO_S.zip](https://github.com/radare/radare2/files/2281153/METRO_S.zip)

Notice the ptr value
```
[0x00000000]> ao
address: 0x0
opcode: bra.b 0x1c
mnemonic: bra.b
prefix: 0
id: 27
bytes: 601a
val: 0x00000000
ptr: 0x00000000
refptr: 0
size: 2
sign: false
type: jmp
cycles: 0
jump: 0x00000000
fail: 0x00000000
stack: null
family: cpu
stackop: null
[0x00000000]>
```

CC @ret2libc 

Seems related to https://github.com/aquynh/capstone/commit/6ed076d41ed89fcdb1f162daa0718fcdd3f35a65 not in master too

**Comment by ret2libc** [comment]
I cannot check myself but just for the records: @maijin said this is not a regression since it was happening in 2.5.0 too. Also, the commit mentioned in the description is actually in master capstone.

It’s probably worth considering filing an issue to capstone repo with test based on cstool with current and expected output.

**Comment by radare** [comment]
if this is an issue in capstone why not report it there? can you test this with cstool and compare with 2 different versions of capstone?

**Comment by ret2libc** [comment]
The referenced test in https://github.com/radareorg/radare2/issues/11056#issuecomment-412365785 is not broken anymore and the binary in the description work as expected (with regards to `jump`/`fail` fields. 

I'm closing this. Thanks!
