### ISSUE TITLE
Project Load files at address configuration redundancy?

### ISSUE THREAD

**Issue by L0gi** [radareorg/radare2#11603]
I am not sure whether I am reading everything right and in case I am missing something it would be nice if someone could point me towards some more detailed documentation.

What exactly is the difference between the configuration variables

bin.baddr, bin.laddr and file.offset
they do have distinctly different descriptions, but it appears that (for projects saving and loading) they follow the same intention of loading a file to a specified offset. 
But none of them seem to actually do that though. And the file is only loaded to a specified offset after saving and then resuming a project, if it was either mapped with the -m command or manually moved using om (if I understand it correctly that means if the rc file contains explicit commands after the #eval section to map the file to a specified offset using the "om" command)?

also, have I missed a mailinglist or something like that that would be more suitable for these types of questions?

**Comment by radare** [comment]
file.offset must be deprecated and should be unused

bin.baddr is writeonly and it is only set by rbin at loading time, there are plans to deprecate it too.

bin.laddr is the load address, aka where the binary is loaded in memory, same as bin.baddr, aka going to be deprecated.

projects need to know many more things that a sngle load address because projects can have many files loaded at the same time with multiple memory spaces, and the use of those variables is conceptually wrong.

Feel free to help us get rid of them with a PR if you want.

**Comment by radare** [comment]
Its fully documented in C

Just in one file

Named project.c

**Comment by radare** [comment]
Theres a project in github about the problems related to projects. Check it out it may be interesting
