### ISSUE TITLE
Add size info to anal class vtables

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/radare2#12601]
Right now, vtables in `aCv` only have an address, but no size. This should be added to the sdb record and also be represented in the size of the flag for the vtable.

**Comment by HoundThe** [comment]
Hey! I started working on this issue #12603 and found out that I can't really look up the actual destination of the method without being sure I am able to dereference memory on the offset because I don't know the size of the table. So I guess I am gonna start here.

Is size mentioned here supposed to be added by the user when adding the vtable to a class? Or an additional command, also I am not sure what the flag mentioned means?

**Comment by thestr4ng3r** [comment]
First of all, the size info should be able to be stored at all, no matter where it will come from later. It should also be settable with the `acv` command, like addr and offset. If possible, `avrr` should fill it too.

Flags in r2 are generic markers at some address and they can also have a size. The flag for a vtable is set here: `https://github.com/radareorg/radare2/blob/master/libr/anal/class.c#L876` (`r_anal_class_set_flag()` doesn't have a size arg yet, this needs to be added and passed to `flg_class_set`)

This function `r_anal_class_vtable_set()` is also the point where the size would have to be stored into the SDB. See how it is done for the address and offset.
