### ISSUE TITLE
radare2 uses too much memory when loading a linux kernel with debug symbols

### ISSUE THREAD

**Issue by Wenzel** [radareorg/radare2#12994]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 29 x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 21013 @ linux-x86-64 git.3.2.1-248-g06ad8f651
commit: 06ad8f651f6929c594bfa847645c701589a2d233 build: 2019-02-04__21:15:06

### Expected behavior
radare2 should not be using that much memory

### Actual behavior
r2 was using 25% of my RAM.
![screenshot_20190204_211949](https://user-images.githubusercontent.com/964610/52235056-60d7cd00-28c3-11e9-9b31-54c167832a61.png)

### Steps to reproduce the behavior 
Please find the binary [here](https://drive.google.com/file/d/1nb9AHMzCYk8rK6RlXlDKtFBG2iKINVEE/view?usp=sharing)

Thanks !

**Comment by Wenzel** [comment]
Update, comparing with GDB for the same file:
![screenshot_20190204_214625](https://user-images.githubusercontent.com/964610/52236223-89ad9180-28c6-11e9-98a7-5adf7634814e.png)

**Comment by devnexen** [comment]
Is it still the case with the current git version ?

**Comment by radare** [comment]
Yep. Nobody touched anything. And that wont probably change in this week because we are focusing on stability for the sunday release.

If u want to inspect the issue use memgrind on linux or instruments on mac and you may get a better understanding of who and why eats all that memory

That will help us identify the problem but i have ideas about the reasons

**Comment by Wenzel** [comment]
I had the time to report the bug, but i don't have it for the investigation.

Meanwhile i switched to gdb.
Thank you for looking at the issue.

**Comment by radare** [comment]
A workaround can be to create a script with the output of rabin2 -r .... kernel > script.r2 and then load the kernel with -i and -n . This will make r2 skip the step of parsing headers and will just load the flags. That should take less memory but didnt tried

**Comment by radare** [comment]
pls try again

**Comment by Wenzel** [comment]
The file is available, like I said.

I retried with the latest radare2, and it's the same, 25% of memory allocated.

**Comment by radare** [comment]
can you try again  now?

**Comment by radare** [comment]
you can use `-e bin.dbginfo=false`' to load faster

**Comment by radare** [comment]
we should use Ht to hold all the src-line info instead of sdb to save memory cc @ret2libc @thestr4ng3r

**Comment by ret2libc** [comment]
@radare I don't know exactly what we should do because I have not tested yet the provided binary, so I'm not sure what is the exact culprit of the excessive memory usage :(

**Comment by radare** [comment]
The dbg info of file:line=addr is stored in sdb. When bin.dbginfo is set (which is by default) thats the only info from dwarf we get. And im aware how heavy it is for storing in memory because its not optimized for memory. Dwarf uses a state machine to hold all this info in a way that is memory friendly. But a hashtable wont be either the best solution here. Maybe rbtree or julian strings.. not sure which would be the simplest/optimal way to store this but it should be mainly queried at file level and addr level.

We may be also able to disassemble all the code associated to a file for example
