### ISSUE TITLE
Retpoline support

### ISSUE THREAD

**Issue by andreafioraldi** [radareorg/radare2#13577]
Hi guys i noted that radare does not recognize the code after a jump to a retpoline as part of a function. They are disassembled but not included in the pdf or VV output.

Example:
```
[0x00000780]> pdf
            ;-- section..text:
            ;-- .text:
┌ (fcn) main 175
│   int main (int argc, char **argv, char **envp);
│           ; var uint32_t arg_0h @ rbp-0x0

...

│           0x00000827      4801e8         add rax, rbp
└       ┌─< 0x0000082a      e936020000     jmp sym.__x86_indirect_thunk_rax
[0x00000780]> s 0x0000082a
[0x0000082a]> pd 10
└      ┌──< 0x0000082a      e936020000     jmp sym.__x86_indirect_thunk_rax
       │╎   0x0000082f      90             nop
       │╎   0x00000830      8b54240c       mov edx, dword [rsp + 0xc]  ; [0xc:4]=0
       │╎   0x00000834      488d35fa0200.  lea rsi, str.login__d       ; 0xb35 ; "login %d\n"

...
```

A jump to a `__x86_indirect_thunk_r??` function can be easily detected and the analysis can continue from the instruction that follows the jump.

I think it is a simple feature but I never touched the r2 codebase and I'm very busy these days so sorry no PR from me ATM :(

I attach the stupid example that i used.

[retpoline.tar.gz](https://github.com/radare/radare2/files/3026634/retpoline.tar.gz)

**Comment by radare** [comment]
The simplest solution for this would be to do the following:

* replace the `jmp thunk` with `jmp reg` by patching the binary or modifying the analysis loop to change the meaning of the jmps to the thunk function.
* if the binary is stripped and we dont have such symbol name, we will need to analyze the code, by emulating it or using signatures to find them.
* This sample is for x86-64, but i've been used to see this on x86-32, but seems to be used as a way to protect against the spectre vulnerability because mjmps are not speculated, while rjmps are. So i assume we will see more and more binaries like this.
* We can probably add a hint to tell r2 that a specific function is a thunk function, as an attribute, like we do for noreturn functions for example.

The problem i see is that all those solutions require several steps depending on the way the binary is constructed, not sure if its better to have this as a helper script for now until we find a common solution for it.

What's strange to me, but maybe makes sense is that the `jmp rax` used for the switch case is not protected, while the one in the `_ITM_deregisterTMCloneTable` which is suposed to be always the same uses this retpoline protection. Do you know the reasons behind that?

And this affects the whole way we identify and analyze jump tables, but i understand gcc8 is using this construction as a replacement for the . I've tested this on Ghidra and it's also failing to analyze this.

**Comment by radare** [comment]
i managed to build your test.c with clang (llvm10) which also supports retpolines

[retpoline-samples.zip](https://github.com/radareorg/radare2/files/3772556/retpoline-samples.zip)

**Comment by radare** [comment]
btw, all that stuff is only for x86-32 and x86-64. But i assume this will come to all the archs soon or late

**Comment by XVilka** [comment]
@radare since you did the retpoline change, can you confirm if this was fixed?

**Comment by radare** [comment]
Yes. This was exactly the bin i used in the testsuite
