### ISSUE TITLE
ELF parsing issue on MIPS binary

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#13737]
IDA and GHIDRA work fine here, but r2 and readelf fail. didnt tried other tools.

https://github.com/radare/radare2-regressions/blob/master/bins/elf/boa-mips

Basically:

* no strings with iz
* no symbols with is
* gp must be resolved with emulation coz no _gp symbol resolved)

**Comment by ulexec** [comment]
The file seems to be truncated and is missing the portion where the section table/ section strings and global string table (.strtab) were. However the ELF header does say that there are sections. 
Therefore, this issue seems to be an attempt to get the sections but it fails since the file is chopped and there is no sections to be found. I can imaging this to have an impact on symbol resolution as well as resolving the strings for those symbols.

**Comment by radare** [comment]
yeah, not having sections is a problem to determine the boundaries where the strings are placed in the binary

**Comment by ret2libc** [comment]
Unfortunately this is, IMHO, the same problem as usual. The bin_elf plugin relies too much on section info, while instead it should first look for segments and then improve those info with the sections, if available. That would require quite a bit of work on bin_elf, but ENOTIME for a while for this.
