### ISSUE TITLE
Endian switch for `pf` formats

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14164]
To be able to specify the endian for every format character/sequence, independently from the current session endian.

cc @ret2libc

**Comment by XVilka** [comment]
@radare what is your opinion on that?

**Comment by radare** [comment]
We have cfg.bigendianbfor this

Just having a host endian syntax should be enough. But i will have to think a bit more to find the right format

**Comment by XVilka** [comment]
In some weird structures some fields have the opposite endianess for whatever reasons.

**Comment by radare** [comment]
I would stay away from this feature for now. Do u have an example of that case? I know some structs that have different endianness knly for some fields depending on the host arcg. Not sure if really matters for real or we want just to dup the struct for each case because at least jn the cases i can think its something done on purpose and nothing generic

**Comment by ret2libc** [comment]
There is already a way to swap endian and it's the `e` format.
```|  e       temporally swap endian```
