### ISSUE TITLE
How does radare allow us to find the offset of a given value in De Bruijn pattern?

### ISSUE THREAD

**Issue by yangboyd** [radareorg/radare2#14830]
Follow this https://www.megabeets.net/a-journey-into-radare-2-part-2/
But I got below:
 r2 -r profile.rr2  -d megabeets_0x2
Process with PID 2630 started...
= attach 2630 2630
bin.baddr 0x00400000
Using 0x400000
asm.bits 64
 -- Temporally drop the verbosity prefixing the commands with ':'
[0x7f86726d11e0]> dc

  .:: Megabeets ::.

Show me what you got:
child stopped with signal 11
[+] SIGNAL 11 errno=0 addr=0x00000000 code=128 ret=0

Any way to find the offset?

**Comment by Maijin** [comment]
Hello @yangboyd 

The article says:

"Did you notice that now our prompt points to 0x41417641? This is an invalid address which represents ‘AvAA’ (asciim little-endian), a fragment from our pattern. radare allows us to find the offset of a given value in De Bruijn pattern."

Did you check the prompt [XXX]> given by radare2 (missing from your paste)

**Comment by yangboyd** [comment]
But It is the address of the "ret", not the chars padded.

r2 -r profile.rr2  -d megabeets_0x2
Process with PID 2630 started...
= attach 2630 2630
bin.baddr 0x00400000
Using 0x400000
asm.bits 64
 -- Temporally drop the verbosity prefixing the commands with ':'
[0x7f86726d11e0]> dc

  .:: Megabeets ::.

Show me what you got:
child stopped with signal 11
[+] SIGNAL 11 errno=0 addr=0x00000000 code=128 ret=0
**[0x00400800]>**

**Comment by ITAYC0HEN** [comment]
Hey :)
Did you compile the file yourself? 
Did you diaable ASLR?

**Comment by yangboyd** [comment]
> Hey :)
> Did you compile the file yourself?
> Did you disable ASLR?

Yes, disabled ASLR:
cat /proc/sys/kernel/randomize_va_space
0

gcc -fno-stack-protector -z execstack -o  megabeets_0x2 megabeets_0x2.c

**Comment by trufae** [comment]
i think the answer was quite misleading and totally not helpful at all, also the ticket is quite old, but didnt went trhough until now

you need to fill the buffer with the deburjn pattern you can use r2 or ragg2 for this:

```
ragg2 -P 120
4141414241414341414441414541414641414741414841414941414a41414b41414c41414d41414e41414f41415041415141415241415341415441415541415641415741415841415941415a41416141416241416341416441416541416641416741416841416941416a41416b41416c41416d41416e4141
```

so when you get the crash you can use `drr` to see where the register points to and the initial bytes of that pattern and then use this command to find out the offset inside the buffer that modifies the register in question:

```
[0x00000000]> wopO 0x41416e41
116
[0x00000000]>
```

and from the shell:
```
0$ ragg2 -q 0x41416e41
Little endian: 116
Big endian: 115
0$
```

note that the value passed to -q is expected to be in a numeric form, because that's how its usually stored in registers. so it's using cfg.bigendian to compute the raw value in memory and give you the offset inside the initial buffer.

This should be documented in the book if it isnt already
