### ISSUE TITLE
Crosscompilation for Windows under Ubuntu fails

### ISSUE THREAD

**Issue by pawlos** [radareorg/radare2#15451]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.2 LTS (WSL)
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | n/a
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0 23255 @ linux-x86-64 git.4.0.0 commit: e97047299af43e9b4e658c246816a2b48bdc087e build: 2019-11-12__21:50:29

### Expected behavior
Cross-compilation succeeds.

### Actual behavior
Cross-compilation fails with an error.

### Steps to reproduce the behavior 
- follow the steps for cross compilation from https://github.com/radareorg/radare2/blob/master/doc/windows.md for Ubuntu

### Additional Logs, screenshots, source-code,  configuration dump, ...
Error during make:
> i586-mingw32msvc-gcc -c  -DUNICODE -D_UNICODE  -MD -D__WINDOWS__=1    -g -Wall -D__WINDOWS__=1 -DR2_PLUGIN_INCORE -I/home/ubuntu/radare2/libr/..//shlr -I/home/ubuntu/radare2/libr/../shlr/zip/include -I/home/ubuntu/radare2/libr -I/home/ubuntu/radare2/libr/include -fvisibility=hidden -I../../shlr/sdb/src//src -DHAVE_FORK=1 -o mem.o mem.c
In file included from /home/ubuntu/radare2/libr/include/r_util.h:13,
                 from mem.c:3:
/home/ubuntu/radare2/libr/include/r_th.h:58: error: expected specifier-qualifier-list before ‘CONDITION_VARIABLE’
mem.c: In function ‘r_mem_memzero’:
mem.c:335: warning: implicit declaration of function ‘explicit_bzero’

**Comment by GustavoLCR** [comment]
Mingw support got dropped a few months ago. 
The official way to build for Windows is using meson+msvc. ([see r2book](https://radare.gitbooks.io/radare2book/content/first_steps/windows_compilation.html))
If you must cross-compile I would suggest using meson and looking at their cross-compilation documentation.
Also as you are under WSL, be careful when cross-compiling, because even though you can natively run windows binaries under it, it will probably break your linux install if the compilation process runs compiled binaries and they write to the WSL folder (as in r2 case, it will run sdb.exe to generate various databases)

**Comment by pawlos** [comment]
@GustavoLCR thanks for the info. I guess then the page [Windows.md](https://github.com/radareorg/radare2/blob/master/doc/windows.md) needs an update.
