### ISSUE TITLE
Implement ecHj to list highlight rules in json format

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15996]
maybe useful for cutter and the webuis

Also, i would like to drop this uppercase 'H' from the naming, and it should be probably  moved to CH because it is stored as an RAnalMeta.

Comments on this @thestr4ng3r  ?

**Comment by c-urly** [comment]
@radare The command should be eCHj?

**Comment by c-urly** [comment]
Hi,
I was able to reach here by including a case for 'j' and calling r_meta_list with rad value as 'j'.

<img width="701" alt="Screenshot 2020-03-03 at 4 17 48 AM" src="https://user-images.githubusercontent.com/14140421/75725215-fed7da00-5d05-11ea-8a93-2684dfa1b339.png">

But, this function give name instead of color as one of the field.
So, Should i create my own function with  same format replacing name field with color?
Or is there any other function which can do this work?

**Comment by radare** [comment]
you may be able to print that rgb:7f0000 in the "name" field easily, but indeed this is a bug. can you send a pr fixing it?

**Comment by c-urly** [comment]
Is this okay?
<img width="546" alt="Screenshot 2020-03-03 at 9 39 29 PM" src="https://user-images.githubusercontent.com/14140421/75794907-80c41380-5d97-11ea-9b79-d4c647625708.png">

Should i convert the offset to hex ?

**Comment by radare** [comment]
Nope. Json doesnt supports hex numbers

**Comment by radare** [comment]
Can u make a pr?

**Comment by radare** [comment]
Done
