### ISSUE TITLE
Allow people to write chart-encoding plugin

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#16272]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open a binary with his own chart encoding because the chart-encoding is not processed instead of the ascii.

For example I can not see the text in visual mode.

**Describe the solution you'd like**
I personally find more convenient to load a module that will change the inernal way that radare2 works instead of add T after each command instead of this issue: https://github.com/radareorg/radare2/issues/414.

For example to write abc: `radare2 -w program -i code-chart-plugin` and then `w abc` instead of `radare2 -w program` and then `wT abc`.

**Describe alternatives you've considered**
I found this issue: https://github.com/radareorg/radare2/issues/414 but in this I can not write my own module. I also do not find very convenient to write many modules.

**Additional context**

**Comment by radare** [comment]
i think what you are refering to is a way to specify the character encoding to write and read strings in r2, right now this is hardcoded and it is not possible to write plugins for this but imho it shold be something inherent to r2 and not done in subcommands like this 'T' thing. uppercase commands are bad. better stick to lowercase.

Maybe a good approach would be to have plugins and a way to select the encoding and make all the functions that process strings inside r2 call that plugin api instead of directly asuming ascii/utf8, same goes for searching strings and so on.

Right now i would tell you to write a core plugin that creates new commands for the stuff you need.

**Comment by trufae** [comment]
This is already possible by using SDB files

**Comment by gogo2464** [comment]
yes @trufae this is an old replicate.
