### ISSUE TITLE
Noisy continous releases

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16329]
following the feeds, it seems like there's a new release in every single commit

https://github.com/radareorg/radare2/releases.atom

**Comment by radare** [comment]
![Screenshot 2020-03-31 at 17 23 25](https://user-images.githubusercontent.com/917142/78046524-8cdfc880-7377-11ea-82b3-39a9989086be.png)

**Comment by kazarmy** [comment]
I think it's best that we delete these draft releases manually. Sure, a script could be possibly be written that deletes them using the GitHub API within a Travis job, but a mistake/bug could spectacularly delete normal releases as well with no way of getting them back unless they are saved somewhere. Even then, it would be difficult to restore them and the timestamps would be off.

**Comment by ret2libc** [comment]
Isn't this fixed @trufae ? I see only one of those continuous build right now. Please re-open if you think otherwise.

**Comment by karliss** [comment]
I'd say its still somewhat noisy. It shouldn't be necessary to create a tag and fake release.

**Comment by ret2libc** [comment]
@karliss What would be the right way to distribute those in your opinion?

Personally, I think we should not generate those things at all. I'm not sure someone is actually using the .deb packages... those .deb packages probably work only on the exact debian version that generated them (from .travis.yml it seems it is debian:stretch, which is quite old and I doubt there are that many oldstable debian user to justify having a continuous build just for them) because of the libc version requirement. @trufae do you remember whether we included those as part of some actual user request or just because we thought it was valuable? I'd vote to drop them.

**Comment by XVilka** [comment]
I suggest not to drop them but package fully static musl-based binaries in
these Deb packages. So they will be compatible with almost everything.

**Comment by ret2libc** [comment]
> I suggest not to drop them but package fully static musl-based binaries in these Deb packages. So they will be compatible with almost everything.

I don't like doing things without reasons. If there is a a real request from more than 1 person it is fine for me to do that. Otherwise, I'm for dropping it. Can't those people use git? Would those people even download those binaries?  As I said, given they are currently built only for debian:stretch, I *highly doubt* anyone is using those. So I don't want to create myself more things to do/bother with if not necessary.
