### ISSUE TITLE
Confusing axf != afx

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16515]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 

### Actual behavior

afx does what i expect it to do axf instead thinks of 'f' as 'from' iand afx as function. 

### Steps to reproduce the behavior 

```
[0x100001018]> afx
c 0x100000ffa -> 0x100001016 jg 0x100001016
c 0x100000ffc -> 0x100001005 jge 0x100001005
c 0x100001003 -> 0x100001016 jmp 0x100001016
c 0x10000100d -> 0x100001016 jg 0x100001016
c 0x100001014 -> 0x100001018 jge 0x100001018
c 0x100001027 -> 0x100004518 jmp sym.imp.strcoll
[0x100001018]> ax?~axf
| axf [addr]      find data/code references from this address
| axff[j] [addr]  find data/code references from this function
[0x100001018]> af?~afx
| afx                                   list function references
[0x100001018]>
```
### Additional Logs, screenshots, source-code,  configuration dump, ...
ive been experimenting a bit with it and realized we can improve the output by grouping the froms and tos, greping by type of reference, etc. also maybe we shuld have READ, WRITE, DATA, CODE, CALL references, this is a DATA is LEA, STR is WRITE, and LDR is READ. im droping this up to discussions

```
[0x10000102c]> afx
c 0x100001053 0x10000105a jg 0x10000105a
C 0x100001055 0x1000041b2 call sym.func.1000041b2
d 0x10000105a 0x100004a98 lea rsi, section.4.__TEXT.__cstring
C 0x100001063 0x100004506 call sym.imp.setlocale
C 0x10000106d 0x1000044ac call sym.imp.isatty
c 0x100001074 0x1000010d4 je 0x1000010d4
d 0x100001076 0x100006280 mov dword [0x100006280], 0x50
d 0x100001080 0x100004a99 lea rdi, str.COLUMNS
C 0x100001087 0x10000447c call sym.imp.getenv
c 0x10000108f 0x1000010a0 je 0x1000010a0
c 0x100001094 0x1000010a0 je 0x1000010a0
C 0x100001099 0x10000441c call sym.imp.atoi
c 0x10000109e 0x1000010c2 jmp 0x1000010c2
C 0x1000010b0 0x1000044a6 call sym.imp.ioctl
c 0x1000010b8 0x1000010c8 je 0x1000010c8
c 0x1000010c0 0x1000010c8 je 0x1000010c8
d 0x1000010c2 0x100006280 mov dword [0x100006280], eax
d 0x1000010c8 0x1000063e8 mov dword [0x1000063e8], 1
c 0x1000010d2 0x1000010fa jmp 0x1000010fa
d 0x1000010d4 0x1000062b0 mov byte [section.10.__DATA.__bss], 1
d 0x1000010db 0x100004a99 lea rdi, str.COLUMNS
C 0x1000010e2 0x10000447c call sym.imp.getenv
c 0x1000010ea 0x1000010fa je 0x1000010fa
C 0x1000010ef 0x10000441c call sym.imp.atoi
d 0x1000010f4 0x100006280 mov dword [0x100006280], eax
C 0x1000010fa 0x10000448e call sym.imp.getuid
c 0x100001101 0x10000110a jne 0x10000110a
d 0x100001103 0x1000062b4 mov byte [0x1000062b4], 1
d 0x100001110 0x100004aa1 lea r13, str.1_ABCFGHLOPRSTUWabcdefghiklmnopqrstuvwx
d 0x100001117 0x100001894 lea rbx, [0x100001894]
c 0x10000111e 0x10000112b jmp 0x10000112b
C 0x100001120 0x1000041b2 call sym.func.1000041b2
C 0x100001134 0x100004482 call sym.imp.getopt
c 0x10000113f 0x1000014db ja case.default.0x10000114c
c 0x10000114c 0x100001120 jmp rax
c 0x10000114c 0x10000114e jmp rax
```

**Comment by ITAYC0HEN** [comment]
For me `axf` was always **a**nalyze **x**refs **f**rom and `axt`  **a**nalyze **x**refs **t**o. 

My real question is why both `axff` and `afx` exists, until I figured that they are different.
`axff` for me was always **a**nalyze **x**refs **f**rom **f**unction. I never used `afx` and actually never knew it was there. I did't think that we should have cross-referencing command in `af` since cross-references belong under `ax`.
But yeah, they are different and it wasn't clear for me at all.

On a general note, I think we should stop with the mystery initials and let the user know what is `c` (it is CODE) or what is `d` (it is DATA).

`axff` shows it right, using the full word (DATA\CODE). The con here, is that it does not use the arrow `->` symbol to explain the directions.
`axff` also showing the flags o the target reference.
```
[0x00001070]> axff
DATA 0x00001091 0x000002e8 section..note.ABI_tag
DATA 0x00001091 0x00001380 main
CALL 0x00001098 0x00003fe0 reloc.__libc_start_main
```
`afx` does use the arrow, but keeps the mystery initials `d` and `c` which is not user friendly. In addition, `afx` shown only addresses and not flags.
```
0x00001070]> afx
d 0x00001091 -> 0x000002e8
d 0x00001091 -> 0x00001380
C 0x00001098 -> 0x00003fe0
```

**Comment by trufae** [comment]
I think the help message is clear. no need to discuss these commands
