### ISSUE TITLE
ambiguity in help of some commands

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#16748]
Right now we use `?` to get the help of a list of commands.
For example:
```
> fd?
Usage: fd[d]  [offset|flag|expression]   # Describe flags
| fd $$         # describe flag + delta for given offset
| fd. $$        # check flags in current address (no delta)
| fdd $$        # describe flag without space restrictions
| fdw [string]  # filter closest flag by string for current offset
```

I would expect to be able to do also:
```
> fdw?
```
and get something like:
```
Usage: fdw [string]   # filter closest flag by string for current offset

`fdw` returns only one flag defined at the current offset which contains 
the string passed as argument. When multiple flags match the string, 
only a random one is returned.

Examples:
> fdw entry
entry0
> fdw try
entry0
```

Does this make sense?
If it does, how to get the help of the command named `fd`? If you do `fd?` you get only the help of all the subset of commands, but not of `fd` itself.

What shall we use? `fd??` ?

cc @karliss @radare @XVilka @thestr4ng3r

**Comment by karliss** [comment]
In my opinion merging the two is acceptable so that there is single help.

```
>cmd?
Usage: fd[d]  [offset|flag|expression]   # summary line

Extended description similar to second section in fdw example.

Examples:
| fd 0x123 # using address
| fd foobar+32 # expression
Subcommands:
| summary lines of all subcommands, in future could be most automatically generated
| fd $$         # describe flag + delta for given offset
| fd. $$        # check flags in current address (no delta)
| fdd $$        # describe flag without space restrictions
| fdw [string]  # filter closest flag by string for current offset
```

In the current help examples and subcommands sections are merged either way is acceptable for me.  There are some commands that already print more detailed description of command for example `afll` and many of the special commands and modifiers like `~`.

Depending on needs the extended description part could contain a few sentences describing the command or description of non-trivial arguments.

**Comment by karliss** [comment]
Searching examples for #16749 I noticed that for some commands full description might be quite long `ae??`. In those cases might be better to keep it separate. So maybe keep description and sub-command list together if description is short or there are no commands otherwise have the command for extended help.

Another potential tool for accessing the help messages is tab complete I wrote some ideas in #16750

**Comment by ret2libc** [comment]
I personally find a bit confusing having sometimes the help of the sub-command embedded and other times separated.

**Comment by ret2libc** [comment]
I'm closing this. For now it seems we are using `?` for longer descriptions on a command. See `wv1?`, `wv2?`, etc. But there is also `wv??` in case you want the detailed help of `wv`, since `wv` is not only a "inner node" but it is also a command itself.
