### ISSUE TITLE
Enable cfg.newshell by default

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#17097]
As title says, this issue is to ask to enable cfg.newshell by default in one of the next releases. I'm not sure how many of you is using it, but I think it is quite stable (sure, there are some issues here and there, but nothing major).

I'm asking this because I would like to remove completely the old parser some time in the future (not too soon, of course), because otherwise we will have a lot of duplicated code everywhere (e.g. the handlers for `@`, `@@`, etc. are duplicated, argv handlers and existing handlers will probably be duplicate, at least in some parts).

**Comment by ret2libc** [comment]
cc @trufae @XVilka @karliss @thestr4ng3r @kazarmy @wargio @ITAYC0HEN @xarkes @condret

It would also be great that, if some of you doesn't have `e cfg.newshell=true` in your .radare2rc, you add it and try to use it for a while. You should not notice any particular difference.

**Comment by trufae** [comment]
sgtm, but i didn't really had much time to test it yet (spent most of the time in vim coding rather than using r2). im fine for switching to the new shell by default, after 1-2 releases, with proper announcement/warning for the users.

I'm curious about:

* R2_CFG_NEWSHELL can be renamed to R2_NEWSHELL (or R2_OLDSHELL) as a way to disable it without having to pass flags to r2 (in case people get their r2pipe scripts broken because of that (which it shouldnt))
* performance changes , but i guess this is hard to say until all commands get argc/argv
* how many people test an option that is not enabled by default (probably < 1%)
* how hard would be for RCOre and io plugins to extend the shell with extra commands with the treesitter path

**Comment by karliss** [comment]
>* performance changes , but i guess this is hard to say until all commands get argc/argv

Performance might actually slightly improve when more commands get converted. As currently when calling comand xyza, newshell will check if commands xyza, xyz, xy exist until it reaches old input handler for x. Once it gets fully converted there will be only one lookup in the command dictionary.
>* how many people test an option that is not enabled by default (probably < 1%)

That's why it will be valuable to have transition period where newshell is enabled by default but can be switched to old one.

>  * how hard would be for RCOre and io plugins to extend the shell with extra commands with the treesitter path

Not sure what you mean by "treesitter path". Plugins will able to register new commands and groups of commands using the same API builtin r2 commands use. This doesn't require modifications to treesitter grammar. It will better than current situation where command dispatcher needs to iterate through all plugins and ask them if they recognize the command.  Plugins will also be able to get error code when comand creation failed due to conflict with already existing command.
New command registration and removal can be done in the existing plugin init deinit methods. It will still be necessary to iterate through all plugins during transition period, but the converted plugins can indicate that they don't use old style command callback by setting it to NULL in plugin description.

**Comment by XVilka** [comment]
I suggest to make it default right after the 4.5.0 release.

**Comment by wargio** [comment]
i think we need to be sure to support almost all the cmds here.

**Comment by ret2libc** [comment]
@wargio consider it runs well on *all* tests. Of course this is not a complete test, but it is already something. Moreover, I think if we enable it just after a release, we can keep testing it for some time and then, if it is not good, always switch back before doing another release.

**Comment by wargio** [comment]
i'm ok to do it for the release after our next one.

**Comment by trufae** [comment]
newshell has been removed
