### ISSUE TITLE
Cannot build on MinGW or Cygwin

### ISSUE THREAD

**Issue by DarrylC03** [radareorg/radare2#17346]
When trying to build (sys/user.sh) for the MinGW or Cygwin environments it fails in the following area:

![image](https://user-images.githubusercontent.com/25788376/88296908-a059d980-cd42-11ea-9a6e-aa440ffab967.png)

Thanks in advance

**Comment by trufae** [comment]
Mingw and cygwin support was removed long time ago

**Comment by ret2libc** [comment]
However you can install radare2 as a regular Windows program by using the radare2-installer in https://github.com/radareorg/radare2/releases/tag/4.5.0 or you can compile it in Windows For Linux Subsystem. If you want to compile radare2 on Windows by yourself, see http://book.rada.re/first_steps/windows_compilation.html .

I'm going to close this bug, because as @trufae said mingw/cygwin is not supported anymore. Thanks!

**Comment by DarrylC03** [comment]
@ret2libc thank you, that is great news. I will use the installer first and do a build later.
