### ISSUE TITLE
Proximity view

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#17483]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
IDA has a nice feature that's called "Proximity View" which allows you to ask "how do i get from this place to this place" via the call graph. It would be nice if r2 supported that as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by trufae** [comment]
Use axt

**Comment by bannsec** [comment]
That appears to just be x-refs. proximity view uses the CFG to find possible paths between two locations, rather than a direct reference.

**Comment by trufae** [comment]
Sorry i mean axg

**Comment by bannsec** [comment]
oh nice. not a big thing but would be nice to be able to specify a starting point for the graph. For instance, if i can get my program already to function x, and want to know specifically how to get from there to function y. That said, I can manually do that with filtering the json or something.

**Comment by trufae** [comment]
axg dest @ source

both addresses can be inside any functtion, it follows bbs inside functions and then xrefs across functions to determine the paths. you can also use axg* to render the interactive visual graph of all the paths to reach a specific point starting from antoher point.

im closing this issue, because i guess that's all you are looking for
