### ISSUE TITLE
I can't install on MacOS 10.11

### ISSUE THREAD

**Issue by mockingcode** [radareorg/radare2#17709]
I'm trying to install it on an older system and this is where it halted:
```
ld: warning: ignoring file /Users/[...]/Desktop/radare2/libr/../shlr/zip/librz.a, file was built for archive which is not the architecture being linked (x86_64): /Users/[...]/Desktop/radare2/libr/../shlr/zip/librz.a
Undefined symbols for architecture x86_64:
  "_inflate", referenced from:
      _r_inflate in zip.o
     (maybe you meant: _r_inflate)
  "_inflateEnd", referenced from:
      _r_inflate in zip.o
  "_inflateInit2_", referenced from:
      _r_inflate in zip.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libr_util.dylib] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Some additional text before the `make` error:**
```
BIN sdb
sdb/sdb: Mach-O 64-bit executable x86_64
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by jace0x21** [comment]
Not sure what the issue was here, but I encountered a very similar error on an M1 Mac. I think this is just the first `ld` command that can fail, so it's a general linking issue. 

For me, I had installed binutils from brew and it had the highest priority in my PATH variable. Moving it to be after Apple bin folders resolved the issue and radare2 was able to build successfully. 

Hopefully, this might help someone else that comes across a similar issue.
