### ISSUE TITLE
Feature Request: Undo Write Operation / Provide Write History

### ISSUE THREAD

**Issue by Semnodime** [radareorg/radare2#17905]
1. Suppose you **open a binary in write mode and patch something**.
2. Then you run the binary to confirm the change worked as intended.
3. You do this over and over again, till I notice that I made a mistake.
     -> Now you need to **undo last edit** (or maybe even further down the line).

I'd be great to **have a history of edits** and a **undo/redo feature for write operations**.

My current workflow is to **yank** portions (with `y) that I will edit later and **paste them back** (with `yy`) when something does not work as intended.

Maybe the `cache mode` allows to achieve this, but as a new user and metaphorically speaking, **a "big red oops! button" would be great**. In case the solution is hidden in the manual, **improve radare2's `??`**.

**Comment by karliss** [comment]
Have you looked at write cache mode `e io.cache.write=true` and `wc` commands?

**Comment by trufae** [comment]
It's usually recommended to make a copy as .bak of the file you are working on to go back the original state. r2 have write cache and undo write support already. it's not hidden. its just not enabled by default because its asuming batch and bulk writes may result on many unneccessary memory usage. The book can probably be improved
