### ISSUE TITLE
Implement pdu

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#18739]
pdu - should be print disasm until (condition: address, type of instruction..)

**Comment by trufae** [comment]
@Lazula wanna check this issue?

**Comment by Lazula** [comment]
Will take this on now.

**Comment by c-urly** [comment]
This we need to implement?

`[0x00006160]> pdu 0x0000616e   ------> until address  ` <br>` 
;-- entry0:
;-- rip:   ` <br>` 
        0x00006160      31ed           xor ebp, ebp   ` <br>` 
        0x00006162      4989d1         mov r9, rdx   ` <br>` 
        0x00006165      5e             pop rsi  ` <br>` 
        0x00006166      4889e2         mov rdx, rsp  ` <br>` 
        0x00006169      4883e4f0       and rsp, 0xfffffffffffffff0  ` <br>` 
        0x0000616d      50             push rax  ` <br>` 
         0x0000616e      54             push rsp  ` <br>` `

`[0x00006160]> pdu op push   ------> until first push INS  ` <br>` 
;-- entry0:   ` <br>` 
            ;-- rip:   ` <br>` 
            0x00006160      31ed           xor ebp, ebp   ` <br>` 
            0x00006162      4989d1         mov r9, rdx  ` <br>` 
            0x00006165      5e             pop rsi  ` <br>` 
            0x00006166      4889e2         mov rdx, rsp  ` <br>` 
            0x00006169      4883e4f0       and rsp, 0xfffffffffffffff0  ` <br>` 
            0x0000616d      50             push rax  ` <br>`

**Comment by trufae** [comment]
if i understand your question properly, you are asking to include the instruction. imho it's easier, and probably more consistent if `pdu X` is the same as `pD X-$$`. so it shouldnt be including that instruction, because it doesnt know the size of it before hand.

If i consider `pdu` kind of `dcu` (as in continue until given address), i expect the debugger to stop in the next instruction. What other people think about this? @Lazula ?

**Comment by Lazula** [comment]
i can open a draft PR to give an idea of my current direction. so far my thoughts are this (copy-pasting the help text):

```
static const char *help_msg_pdu[] = {
        "Usage:", "pdu[aceios]", "Disassemble instructions until condition",
        "pdua", " [addr]", "disassemble until address",
        "pduc", "", "disassemble until call",
        "pdue", " [expr]", "disassemble until esil expression",
        "pdui", " [inst]", "disassemble until instruction (e.g.: add esp, 0x20)",
        "pduo", " [opcode]", "disassemble until opcode (e.g.: mul)",
        "pdus", "", "disassemble until syscall",
        NULL
};
```

`pdu` is just a prefix and not a command (it runs `pdu?`), and you use the last letter to specify the condition type. `pdua` would not include the instruction starting at the given address, but all others would include the terminating instruction. instruction-based conditions could just be string comparisons, no need to assemble.

current concerns are:

* infinite printing, fallback condition - force stop at 0xffff prints?
* idk about the esil api so it might be more complicated than a simple search

so far i've just made a copy of `r_core_print_disasm()` to modify, but i would like to see all the current disasm functions refactored and this could be included. tangential but my thoughts for that are to have a central function that can optionally be dispatched from smaller ones that set up arguments so that certain uses are more clear in the code base.

**Comment by trufae** [comment]
@Lazula your proposal lgtm. about your concerns.

* infinite printing: that's an issue in other commands, there's a maxsize limit for stuff like `px 0x80808080` and also, RCons will not print if the output is really big without asking the user.
* esil api is pretty easy, but we probably want to have some high level definitions on top of it to make it easier

**Comment by trufae** [comment]
@c-urly @Lazula anyone? if u have something ready plese submit a PR

**Comment by trufae** [comment]
Merged in! thank you <3
