### ISSUE TITLE
Custom alias autocomplete is not working

### ISSUE THREAD

**Issue by alex-bender** [radareorg/radare2#19397]
tab completion is not working for user defined aliases
```
[0x00000000]> $test=afl
No such alias "$t"
[0x00000000]> $t<TAB>
No such alias "$te"
[0x00000000]> $te<TAB>
No such alias "$tes"
[0x00000000]> $tes<TAB>
[0x00000000]> $test<TAB>
afl
[0x00000000]> $test
```

**Comment by trufae** [comment]
cc @Lazula

**Comment by Lazula** [comment]
Hi, this is happening due to a new config variable that tries to automatically show help when you tab complete a command (see #19295). So, for example, when you try to tab complete with `$t` in the line buffer it runs `$t?`, which has no meaning.

Aliases currently do not support tab completion at all. Before that PR, tab just did nothing. For now, you can use `$*` and `$**` to show all aliases. I'm currently working on support for this, but I wanted to inform you as soon as I found the cause.
