### ISSUE TITLE
WSL and R2 issue Cannot find function at 0x00001080 sym. and entry0 (aa)

### ISSUE THREAD

**Issue by gitMushy** [radareorg/radare2#19399]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
radare2 4.2.1 0 @ linux-x86-64 git.4.2.1
Linux x86_64
```

## I created a c program and compiled it, when i load it into r2 on WSL and do aaa i get the error cannot find function at 0x00001080 sym. and entry 0 (aa)

afl  does not display function names
however because i know the function names i can still s sym.main to jump there. 

is this a bug for me or is this just an issue with WSL. There also appears to be an issue with the output address but when clicked to move them to input bar the address changes to a completely different address. 

again wondering if this is just a WSL issue or i installed wrong.

**Comment by trufae** [comment]
Theres no issues with r2 on wsl. It works well. Can you share the binary you are trying to analize? How did you installed r2? From source?

**Comment by krsche** [comment]
I'm having similar problems on WSL1 Ubuntu 20.04 when using the apt packaged version (4.2.1).  
`uname -a`: `Linux pc 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux`  

`aaa` and `aaaa` yields only the following:
```
[0x000010a0]> aaaa
[Cannot find function at 0x000010a0 sym. and entry0 (aa)
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Finding function preludes
[x] Enable constraint types analysis for variables
```
with `afl`:
```
[0x000010a0]> afl
0x000010d0    4 41   -> 34   sym.deregister_tm_clones
0x00001100    4 57   -> 51   sym.register_tm_clones
0x0000118d    4 103          fcn.0000118d
0x000011f8    4 118          fcn.000011f8
0x00001272    1 47           fcn.00001272
```

Trying to clone and install from git - running `./sys/install.sh` gives me the following error:
```
- krsche@x radare2 (master) $> git co 5.5.0
Updating files: 100% (143/143), done.
Note: switching to '5.5.0'.
...
HEAD is now at ab6353c5c Release 5.5.0 - 希 Nozomi
- krsche@x radare2 (5.5.0) $> ./sys/install.sh
: not foundll.sh: 2:
./sys/install.sh: 16: Syntax error: word unexpected (expecting "in")
```

**Comment by trufae** [comment]
Which shell do you use? This script works well on any standard posix shell like bash, dash, pdksh, zsh, ...

**Comment by krsche** [comment]
@trufae I'm just using bash. Behaviour is really strange to me as well.
I'll try to find time this or next week again to have a deeper look and compare the behaviour with a native linux install.

**Comment by trufae** [comment]
i use r2 on wsl every day and never experienced such issue. can you try running the script with `bash sys/install.sh` instead?

**Comment by trufae** [comment]
also any reason to build 5.5.0 and not HEAD?

**Comment by krsche** [comment]
Alright, so the error I reported was due to the shell scripts being checked out with `CRLF` line endings.
I use the Windows filesystem from wsl for my repos, which usually works fine (this is also why I still use WSL1 most of the time).

Build and install works fine after converting the line endings to `LF`.
Is there a usecase for running the scripts under windows? If not, would it be feasible to add something like `*.sh text eol=lf` to the `.gitattributes`? I guess that would've prevented my error.

Note: It wasn't enough to convert just all `.sh` files - Found out there are some scripts with different descriptors, so I just converted the whole repo. 

Reason for 5.5.0 was that it's the latest released one, so I figured it might be more stable than the latest master. :)

**Comment by trufae** [comment]
Oh wow! That crlf bug wasnt expected :D thanks for pointing it out because the error message is not helping.

you can configure git in the installation wizrad or configure it following the instructions here to make a clean clone 

https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

releases are mean to be used for distros and as well by users who want to use a specific version just because whatever script or plugin worked well in there.

ideally everyone should be using r2 from git. As its more stable than the releases (because people test releases so the fixes go into the git) the testsuite is mature enough to trust whats commited without breaking things, so master should be stable
