### ISSUE TITLE
How to insert asm code in file without overwriting

### ISSUE THREAD

**Issue by lkz0ne** [radareorg/radare2#19590]
I am learning reverse engineering tools. I notice that when you need to patch some file (as least in visual mode) you need to overwrite instructions, i.e. when using shift+a in visual mode or i in visual mode.

Theres a way to insert asm code without need to overwrite some other?

Preferable writing code in asm and not in hex machine language.

**Comment by lasek0** [comment]
there is probably few issues with that approach. If You want to overwrite instruction without overtiring following instructions this needs to shift following code few bytes forward, and this movement will broke whole program because addresses (for example of function / tables / etc..) are no longer valid.

I know one way (or trick) to create such patch, but it requires some free space in binary (You can find it on still allocated segment after end of program) an then in place when there is instruction You want to change You create an jump to that free space (of course You probably need to overwrite few more instruction but You can restore it in that free space you find) in that free space You can patch Your instruction add few more or do whatever, and then You need to continue program by jump back to instruction after Your jump (be careful to jump to valid instruction to properly continue program)

for example:
```
│           0x000011a3      c745e4d00700.  mov dword [var_1ch], 0x22b
│           0x000011aa      8b45e4         mov eax, dword [var_1ch]
│           0x000011ad      89c6           mov esi, eax
│           0x000011af      488d3d4e0e00.  lea rdi, [0x00002004]       ; "%d" ; const char *format
│           0x000011b6      b800000000     mov eax, 0
```

I want to change mov esi, eax with some other instruction **(this case probably does not have any meaning and will not work 
properly, but illustrate the idea)** and I found an emply space in that address 0x12a0


patch wanted instuction by oferriting few:
`"wa jmp 0x12a0" @ 0x000011ad`

```
│           0x000011a3      c745e42b0200.  mov dword [var_1ch], 0x22b
│           0x000011aa      8b45e4         mov eax, dword [var_1ch]
│       ┌─< 0x000011ad      e9ee000000     jmp 0x12a0
..
│       │   0x000011b6      b800000000     mov eax, 0
```

create an writable free space in r2
` o - 0x12a0 rwx`

then @ address 0x000012a0 I write code:
`"wa mov esi, eax; nop; nop; nop; lea rdi, [0x2004]; jmp 0x000011b6" @ 0x000012a0
`

```
pd 6 @ 0x12a0
        ╎   0x000012a0      4089c6         mov esi, eax
        ╎   0x000012a3      90             nop
        ╎   0x000012a4      90             nop
        ╎   0x000012a5      90             nop
        ╎   0x000012a6      488d3d570d00.  lea rdi, [0x00002004]       ; "%d"
        └─< 0x000012ad      e904ffffff     jmp 0x11b6                  ; main+0x4d
```


so the cpu executes folowing code in linear fashion:
```
0x000011a3      c745e42b0200.  mov dword [var_1ch], 0x22b
0x000011aa      8b45e4         mov eax, dword [var_1ch]
0x000011ad      e9ee000000     jmp 0x12a0
0x000012a0      4089c6         mov esi, eax
0x000012a3      90             nop
0x000012a4      90             nop
0x000012a5      90             nop
0x000012a6      488d3d570d00.  lea rdi, [0x00002004]       ; "%d"
0x000012ad      e904ffffff     jmp 0x11b6                  ; main+0x4d
0x000011b6      b800000000     mov eax, 0
...
```

You need to be careful by doing this because overall state of function must be preserved (for example stack or some registers).

not sure if This is what You want approach.

**Comment by lkz0ne** [comment]
Wonderful. All makes sense now. Thank you sir.

**Comment by lasek0** [comment]
Do You need any more explanation on that topic? maybe You can close that issue.
keep reversing and have a nice day.
