### ISSUE TITLE
pipes in r2pipe

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#19606]
using r2pipe ends up calling `r_core_cmd_str` which slurps the output from RCons and results on empty files if used the redirection character. Somehow this is not expected behaviour so it should be fixed

Works fine when used via spawn

![IMAGE 2022-01-19 17:54:23](https://user-images.githubusercontent.com/6431515/150177337-4b48e771-6a01-49c3-a2ab-243d35589d64.jpg)

But fails when used from inside r2:

`r2 -i foo.py /bin/ls`

where `foo.py` contains:

```
import r2pipe
r2pipe.open().cmd("px > a.txt")
```

then `a.txt` is empty. 👻

**Comment by Lazula** [comment]
Some info that hopefully helps diagnose the issue:

`echo 'import r2pipe; r2pipe.open("/bin/ls").cmd("x > a.txt")' > foo.py; r2 -i foo.py -` works but `echo 'import r2pipe; r2pipe.open().cmd("x > a.txt")' > foo.py; r2 -i foo.py /bin/ls` does not. The difference is whether you pass the filename in `r2pipe.open()` or as an argument to r2.

I got output by using `r2pipe.open("-")` instead of `r2pipe.open()`, so there may be an issue with not passing the filename properly.

**Comment by Lazula** [comment]
Example:

![image](https://user-images.githubusercontent.com/26179473/151366721-186b716f-ea8b-4e8a-a075-5f2dcbef97b3.png)

**Comment by trufae** [comment]
Open() means reuse the current session and open("-") means create a new process wirh new environment. They are completely different things

**Comment by Lazula** [comment]
I see, I wasn't clear on that. In my testing the order of internal commands differs depending on which one you use. I traced the execution and it looks like things follow the expected path once in r_cons_pipe_open() and r_core_cmd_subst(), so I think things are going wrong before then. Not sure what to look for here.
