### ISSUE TITLE
remove the c code on charset plugins?

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#19693]
I realized that for some performance issue, somebody has written some c code to make the charset plugin faster.

To be honest it does not really match with my personnal vision of the charset plugins.

I do not like that. Text was only to allow not dev people to configure their charset. If people do C and text together, the codebase is just a bad C codebase. Nothing else.

I would like to have your opinion and then I could fix it.

**Comment by gogo2464** [comment]
We can remove text. We can remove C code. I am open to everything. But please. Not together.

**Comment by trufae** [comment]
The C code you are talking about is autogenerated at compile time by sdb. It's enabled by default on acr builds and disabled for meson ones. The reason for having them in C is not about performance, but portability. Because this way you can ship a single executable with all the sdbs inside the same binary. It's doing the same for all the other sdb files that are distributed with radare2.

You can still load and use plaintext files or sdb databases, but the user can decide at compile time which charsets to include and if they should be embedded inside the executable as native code instead of data.

**Comment by gogo2464** [comment]
Ah fine! 

Then I think my update of r2book is wrong https://github.com/radareorg/radare2-book/commit/53c3053ee39f56c30b5855d577982e0d6f99f586

**Comment by trufae** [comment]
That's fine, your instructions describe how to add a plugin in the core, but it should be possible to load from file too. Let me give it s try and add a test just in case

**Comment by trufae** [comment]
i found a bug that was priorizing the compiled-in charsets before the files passed, but it works now, please add tests to proof your point. it will be good to make charsets configurable at compile time like it happens with the configure-plugins. so the list of inlined charsets is smaller.

**Comment by gogo2464** [comment]
> i found a bug that was priorizing the compiled-in charsets before the files passed, but it works now, please add tests to proof your point. it will be good to make charsets configurable at compile time like it happens with the configure-plugins. so the list of inlined charsets is smaller.


So it is fine I could re-update the content now?

**Comment by gogo2464** [comment]
And let only the text file in the tutorial?

**Comment by gogo2464** [comment]
https://github.com/radareorg/radare2/pull/19700/files#diff-bd5e79f50987fdbdde81f939cbc815461a8d0ab6e3ebd7860dd06ec6c57e9f35R11 this is not fine. I really think you manually added some c code into the PR. Else you should not have merged it. I do not understand.
