### ISSUE TITLE
[BUG] iz misses strings in .rdata (found by IDA)

### ISSUE THREAD

**Issue by srobertjames** [radareorg/radare2#19727]
Sample binary is at https://github.com/utcoalition/utcctf-19/blob/master/rev-hactivate/rev.exe .

radare2 is able to find some strings from .rdata, but for some reason, misses others:

```
$ r2 rev.exe 
[0x004041e7]> iS~rdata
1   0x00004200  0x2200 0x00405000  0x3000 -r-- .rdata
[0x004041e7]> x 16 @ 0x405414
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00405414  7574 637b 0000 0000 0a66 6169 6c65 6421  utc{.....failed!
[0x004041e7]> iz~failed # r2 finds this string
12  0x0000461c 0x0040541c 8   9    .rdata  ascii   \nfailed!
[0x004041e7]> iz~utc # but misses the "utc{" string
84  0x0000579e 0x0040659e 61  62   .rdata  ascii   ?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z
```

The missing string is only 4 chars long, so perhaps there's a minimal string length setting.  However, I couldn't find one, neither via `e` or online.  `e bin.minstr` was set to 0; setting it to 1 solve the problem.

**Comment by trufae** [comment]
Yes, the minstr is the reason for not spotting this string. rdata can contain lots of trash, not just strings, and 4 printable chars could be pointers or so, if you dont want to rely on this behaviour you have different options to use depending on your needs.

* use anal.strings (instead of bin.strings) that will find only strings that are referenced from the analysis
* lower the bin.minstr value
* use .izz* to load more strings from static

There are always ways to improve the default behaviour, but sometimes is tricky when trying to handle too many file formats and architectures at once. One option could be to change those minstr settings at loading time depending on:

* fileformat
* architecture
* ..

do you have any proposal for this to improve the defaults?

**Comment by srobertjames** [comment]
Thanks.  Lowering `bin.minstr` doesn't seem to help (see below).  Also, the default bin.minstr isn't 5, it's 0.  Am I making a mistake?

```
[0x004041e7]> e bin.minstr
0
[0x004041e7]> iz~utc
84  0x0000579e 0x0040659e 61  62   .rdata  ascii   ?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z
[0x004041e7]> e bin.minstr=1
[0x004041e7]> iz~utc
663 0x0000579e 0x0040659e 61  62   .rdata  ascii   ?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z
[0x004041e7]> e bin.minstr
1
```

**Comment by trufae** [comment]
Fixed in master

**Comment by srobertjames** [comment]
Glad it's fixed -- what was the cause?

**Comment by trufae** [comment]
Yeah me too! Thanks for reporting!

the reason was that the code searching for strings was incorrectly handling utf32 strings and skipping too much bytes after a false positive finding. So it was not even checking the bytes constructing that string.

i fixed that and added tests. if you find any other issue related to strings let me know! I would like to refactoring all this code but i think we still need more tests to ensure non-utf8 charsets and ebcdic and such. 

Thanks!
