### ISSUE TITLE
Renasas RL78 disassemble 

### ISSUE THREAD

**Issue by Markusclement** [radareorg/radare2#19843]
## Description
Hi
New to Radare and really enjoying it so far

I’m trying to disassemble a RL78 MCU Ihex binary and am able to get it into r2 
Using r2 Ihex://rl78mcu.hex but the disassembly doesn’t look like rl78 code
I’ve searched the project and see references to RL78 but can’t figure out how to get it to work

I’ve tried r2 -a rl78 Ihex://rl78mcu.hex but no difference 

any suggestion would be appreciated 

thanks 

*Please describe what are you missing or wanting to be improved*

*Provide images, ascii-art, test files and anything that may help us understand your request*

**Comment by trufae** [comment]
Unfortunately there's no support for this architecture in r2 yet. You can list them with rasm2 -L, rasm2 -LL and r2pm -s asm

**Comment by Markusclement** [comment]
> Unfortunately there's no support for this architecture in r2 yet. You can list them with rasm2 -L, rasm2 -LL and r2pm -s asm

Ok thanks. I’d seen references to RL78 in some of the sources so I figured I was just missing a step. Will try your suggestions

**Comment by trufae** [comment]
I don't see any reference to RL78 in the source code of r2 :?

Anyway, it's supported by binutils, so I just spent 5 min to write the plugin. so now you can do `r2pm -ci rl78` and then `r2 -a rl78 hex://....`

The plugin just disassembles. so it will consider all instructions invalid and that's why they are printed in red. its pretty easy to improve that plugin and extend it to support emulation thru ESIL and so on. I keep that part for you if you are interested, I have no bins to test or knowledge on this architecture (or time ;D) to go deeper right now.

let me know if you need some help

**Comment by Markusclement** [comment]
ThAnks
![9F896D3D-A010-4796-BEE7-F7FD38BE043B](https://user-images.githubusercontent.com/101952102/159191440-ed2dc2a6-54cf-4c30-9a64-55bfc936c83c.png)
![C335C064-3842-4BBE-8CF1-A2289EC1802D](https://user-images.githubusercontent.com/101952102/159191444-746584f0-7691-447d-9027-ad10cb4008a0.png)
. Will try it out

the references I’d seen where in these places
