### ISSUE TITLE
xrefs missing from iOS Framework file

### ISSUE THREAD

**Issue by phwd** [radareorg/radare2#19863]
## Environment

```
Wed Mar 23 06:53:09 CDT 2022
radare2 5.6.5 27597 @ darwin-x86-64 git.5.6.4
commit: b0f1c3716fb50ab9d8bf010f0113f46ac92e1240 build: 2022-03-16__14:09:40
Darwin x86_64
```

## Description

Facebook.ipa (https://apps.apple.com/us/app/facebook/id284882215) Framework file FBSharedWithExceptionsEnabledFramework is missing xrefs which appear in Ghidra/Hopper

## Test

[FBSharedWithExceptionsEnabledFramework.zip](https://github.com/radareorg/radare2/files/8332750/FBSharedWithExceptionsEnabledFramework.zip)

unzip FBSharedWithExceptionsEnabledFramework.zip
r2 -e emu.str=true -A FBSharedWithExceptionsEnabledFramework
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze all functions arguments/locals
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references (aao)
[x] Parsing metadata in ObjC to find hidden xrefs
[x] Found 11098 objc xrefs in 0 dwords.
[x] Finding and parsing C++ vtables (avrr)
[x] Finding xrefs in noncode section (e anal.in=io.maps.x)
[x] Analyze value pointers (aav)
[x] ... from 0x0 to 0xc2c000
[x] 0x00000000-0x00c2c000 in 0x0-0xc2c000 (aav)
[x] Emulate functions to find computed references (aaef)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information (aanr)
[x] Use -AA or aaaa to perform additional experimental analysis.
 -- git pull now
[0x00000000]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze all functions arguments/locals
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references (aao)
[x] Parsing metadata in ObjC to find hidden xrefs
[x] Found 11258 objc xrefs in 0 dwords.
[x] Finding and parsing C++ vtables (avrr)
[x] Finding xrefs in noncode section (e anal.in=io.maps.x)
[x] Analyze value pointers (aav)
[x] ... from 0x0 to 0xc2c000
[x] 0x00000000-0x00c2c000 in 0x0-0xc2c000 (aav)
[x] Emulate functions to find computed references (aaef)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information (aanr)
[x] Finding function preludes
[x] Enable constraint types analysis for variables
[0x00000000]> iz~openssl cert
29396 0x01478883 0x0152c883 27   28   35.__RODATA.__cstring        ascii   openssl cert verify error:

The above string has an reference in a function which is picked up in Ghidra and Hopper Disassembler

**Comment by trufae** [comment]
r2 can catch this xref with just running `aae`. that's an issue with the default/standard and dummy `aaaa` which is slow and if you know what you are doing is better to never use it.

<img width="840" alt="Screenshot 2022-03-23 at 15 57 22" src="https://user-images.githubusercontent.com/6431515/159728862-bb7fa487-aeaa-4d38-bfbc-d17335430041.png">

The reason why `aaa` doesnt catch this xref is because this is a computed reference, so it requires emulation to find it, the only analysis commands that do that are: aae, aaef and sixref.

The problem is that `aaa` runs `aaef`which only emulates the functions that has been analized. and in this case the code referencing this string wasnt identified because `aaa` only runs on public symbols. So you have different solutions here:

* Use aap = to find new functions by searching for prelude patterns (aap runs in `aaaa`/`-AA` but not in `aaa`/`-A`)
* Use e anal.hasnext=true to also analyze consecutive functions

After this running `aaef` will spot the reference. 

Also, as a side note, this is a string reference, so enabling `e anal.strings=true` will result on better disassembly as it may flag every string referenced accordingly.

**Comment by trufae** [comment]
As a solution I would suggest to make `aap` run in `aaa`. hopefully wont result on false positives

**Comment by phwd** [comment]
Thank you very much this is very informative.
I'll self close this to clear this off the issue list
Have a good day and much appreciated again

**Comment by trufae** [comment]
https://github.com/radareorg/radare2/pull/19866

I did a blind fix. Can you try again? Im busy with other stuff right now. The fastest analysis command for arm64 is "sixref" which seems to fail to find this xref. I'll look into that too.

thanks for reporting and your time and patience :)

**Comment by phwd** [comment]
Looks good to me

```
radare2 5.6.7 27650 @ darwin-x86-64 git.5.6.6
commit: b914887fcd382805759ed927ffb879d7b1cad7dc build: 2022-03-24__12:52:28

r2 -2 FBSharedWithExceptionsEnabledFramework 
 -- Charlie! We are here.
[0x00000000]> aaa
[0x00000000]> iz~verify err
29396 0x01478883 0x0152c883 27   28   35.__RODATA.__cstring        ascii   openssl cert verify error: 
[0x00000000]> s 0x0152c883
[0x0152c883]> pd 1
            ;-- str.openssl_cert_verify_error:_:
            ; STRING XREF from fcn.0040ce1c @ 0x40d280
            0x0152c883     .string "openssl cert verify error: " ; len=28
[0x0152c883]> s 0x40d280
[0x0040d280]> pd 1
│           0x0040d280      000c2291       add x0, x0, 0x883           ; 0x152c883 ; "openssl cert verify error: "
```

Thank you very much!
