### ISSUE TITLE
need dynamic *disable threads* option

### ISSUE THREAD

**Issue by b1gcat** [radareorg/radare2#20088]
As '[iaito](https://github.com/radareorg/iaito)' says, it does not support threads, and must compile radare2 with --disable-thread options.

it's not convenient, that I cannot use r2pm or pip to install and have to rebuild radare2 

can we have a option to disable threads before running r2?

**Comment by trufae** [comment]
Unfortunely this is not possible, because the thready-r2 uses TLS variables, which are defined at compile time. But now r2 have some more thread-friendly primitives that will permit to use it properly from iaito. So hopefully, after the release of r2-5.7, i can spend some time in iaito-land and solve that anoying issue
