### ISSUE TITLE
Is it possible to make a call through r2pipe in a macro?

### ISSUE THREAD

**Issue by pipothebit** [radareorg/radare2#20209]
I try to create a macro to measure execution times of code blocks through esil without success.
I have not found any reference to whether or not this can be done with a macro and although I understand that given the versatility of r2 there are many ways to do this, I wanted to know if it was possible to do it with macros.

Being new to using r2, is there any other place to ask simple questions about how to use r2 or problems like this?
```
env SCRIPTS_DIR=radare2/scripts
(aecu x; env __aecu_START=$(!date +"%s"); aecu $0; #!pipe node $SCRIPTS_DIR/util.elapsed.js)
.(aecu 0x00003314)
```

**Comment by trufae** [comment]
you may want to quote the whole second line to avoid undesired special chars like this:

```
cd radare2/scripts
"(aecu x; env __aecu_START=$(!date +"%s"); aecu $0; . util.elapsed.js)"
.(aecu 0x00003314)
```

but you can also escape the semicolons. the $env variables are not substituted, also the $() wont work as in the shell. You should better post this script into the discussions tab so we can have a better place to define and find better ways to do what you want.

btw, r2 have a `date` command , as well as a timing and timeout features:

* `?t aaa` -> show how much time took to run this command
* e anal.timeout=3 -> will break the analysis if it takes more than 3s (that probably doesnt works with eacu, but should be tested and imho that would be an expected behaviour).

Actually we may also want to extend this "continue-until-timeout" to the native debugger, not only with esil emulation. what do you think?

So pleaes checkout (and move the topic) to this site instead: https://github.com/radareorg/radare2/discussions
