### ISSUE TITLE
Better segregation of the embedded libmagic code and radare2 code

### ISSUE THREAD

**Issue by xambroz** [radareorg/radare2#20543]
## Description

Radare2 contains ancient version of libmagic from "file" utility. The embedded version is inplace patched with r2 features so it is not easy to update it or use system library. Purging the libr/magic directory from the libmagic artifacts and using USE_LIB_MAGIC compile variable results in the compilation error of missing r_magic_from_ebcdic
https://kojipkgs.fedoraproject.org//work/tasks/8722/90388722/build.log
 
Note that Fedora package is purging some stuff from the libr/magic directory so it is quite possibly also wrongly purging the r_magic_from_ebcdic ... still it would be nice having there is the option  USE_LIB_MAGIC to have some easy way to purge the common embedded libmagic stuff so it can be sure what code is being used. It would be nice to have the libmagic and radare2 code separated.

```
libr/hash/libr_hash.so.5.7.6 libr/magic/libr_magic.so.5.7.6 libr/socket/libr_socket.so.5.7.6 libr/syscall/libr_syscall.so.5.7.6 shlr/libr2java.a shlr/libr2yxml.a -ldl -lm -pthread -lutil /usr/lib64/liblz4.so /usr/lib64/libz.so /usr/lib64/libssl.so /usr/lib64/libcrypto.so -lutil -Wl,--end-group
../libr/bin/format/mach0/mach0.c: In function ‘get_sections’:
../libr/bin/format/mach0/mach0.c:2376:26: warning: argument 1 range [18446744071562067969, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
 2376 |         if (!(sections = calloc (bin->nsects + 1, sizeof (struct section_t)))) {
      |                          ^
/usr/include/stdlib.h:543:14: note: in a call to allocation function ‘calloc’ declared here
  543 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^
../libr/bin/format/mach0/mach0.c: In function ‘get_sections_64’:
../libr/bin/format/mach0/mach0.c:2376:26: warning: argument 1 range [18446744071562067969, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
 2376 |         if (!(sections = calloc (bin->nsects + 1, sizeof (struct section_t)))) {
      |                          ^
/usr/include/stdlib.h:543:14: note: in a call to allocation function ‘calloc’ declared here
  543 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^
/usr/bin/ld: /tmp/ccKYBUR7.ltrans6.ltrans.o: in function `sections.lto_priv.35':
/builddir/build/BUILD/radare2-5.7.6/redhat-linux-build/../libr/bin/p/bin_s390.c:235: undefined reference to `r_magic_from_ebcdic'
collect2: error: ld returned 1 exit status
```

**Comment by xambroz** [comment]
Specifically there is code for r_magic_from_ebcdic in the libr/magic/ascmagic.c, which is not in the current libmagic and is probably radare2 specific. It would be better to have it in some separate radare2 specific file.

**Comment by trufae** [comment]
There's nothing r2 specific in r2's libmagic, it's a copy of the implementation in OpenBSD, which is incompatible with the GNU one. I found, and reported a couple of vulnerabilities in this code at the time, and the reason is because the LOC is pretty low, compared to what GNU provides. This is 5KLOC vs 20KLOC.

Another reason for shipping our own version of libmagic is because the GNU one has been vulnerable for several years (more than 4 iirc) on main distros out there. And i dont want to make r2 depend on distros or systems to work reliabily anywhere, r2 should be self contained and easy to build and run anywhere.

Apart from that i understand the concerns of distros of not shipping duplicate implementations of the same. But it's also important to note that bsd libmagic is incompatible with gnu libmagic, not just at api level, but also at implementation. but i try to keep the signature database as small and compatible with both implementations just to please distros. but it will be also good to benchmark both implementations because iirc last time i tested gnu magic was kind of 20x slower than our implementation.

I'm not proud of the code quality of the bsd implementation, i just pick it because it was smol, fast, secure and did the job well. the gnu implementation have too many features that we don't need. And right now @iotaaxel is working on removing the global variables in this code (because that was not suposed to be a library, but a commandline tool at the time this code was written).

As long as changing the API or ABI conflicts with the current release model in r2land, the change must happen in r2-5.8. But i would like to get rid of this ebcdic incompatibility and maybe perform some more comparisons between gnu magic and our magic (performance and compatibility-wise) to clarify that.

The `r_magic_from_ebcdic` function can be implemented in libr_magic, which can link to libmagic for the rest. i will submit a PR fixing that but wont be merged until 5.7.9 is on the works.

thanks for reporting!

i will also take care of the other warnings you reported in the log

**Comment by trufae** [comment]
btw, r_magic_from_ebcdic is only used from RBin.s390 which can be workarounded with an ifdef. also a CI job building and testing r2 with gnu libmagic may be good to have too 👍

**Comment by trufae** [comment]
Should be fixed in master, its tested by the CI. turns out now gnu libmagic is 2x faster, but the results differ. need to test further for proper compatibility. but i consider this ticket as solved

thanks for reporting!

**Comment by xambroz** [comment]
Hello,
works for me, thank you.
I have used ddf483893e92f9edcd3d65f1098231b000bfe28a as a patch to 5.7.6 release + I have to keep stub of stripped magic.c and ascmagic.c in order to work with system-installed gnu libmagic.
https://koji.fedoraproject.org/koji/taskinfo?taskID=90615989

Michal Ambroz

**Comment by trufae** [comment]
yes. libr_magic is the library that provides the logic behind libmagic, or acts as a wrapper of libmagic if built this way. ill find some time next week to take care on the surfaced issues that made libmagic results differ. thanks for reporting!
