### ISSUE TITLE
Can't run radare compiled with libcapstone4 or syscapstone

### ISSUE THREAD

**Issue by diaevd** [radareorg/radare2#20690]
## Environment

```sh
Tue  6 Sep 15:15:08 MSK 2022
r2: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
Linux x86_64
```

## Description

Can't start on ubuntu 22.10 because libcapstone3 is removed from disto.

Install with
./sys/install.sh --with-syscapstone
or
./sys/install.sh --with-capstone4

Don't resolve problem. r2 compiled just fine but linked to libcapstone.so.3

Try to install libcapstone3 from ubuntu 22.04
Package: libcapstone3                    
Version: 4.0.1+really+3.0.5-1build1

Produce error:
```sh
$ r2 -v
r2: symbol lookup error: /usr/local/lib/libr_main.so: undefined symbol: r_sys_env_init
```

How to compile r2 with libcapstone4 correctly?

## Test

Install with
./sys/install.sh --with-syscapstone
or
./sys/install.sh --with-capstone4

**Comment by trufae** [comment]
Looks like you have multiple installations of r2 and your builds are not using rpath or had a proper librarypath defined. The error is unrelated to capstone

**Comment by diaevd** [comment]
No, only one installation of r2. Installed  from git sources by ./sys/install.sh after make uninstall && make purge

```sh
diabolo@veles:~$ which r2
/usr/local/bin/r2
```

no radare2 packages or anything else

**Comment by trufae** [comment]
the function `r_sys_env_init` is defined in libr/util/sys.c in 2020, so it doesnt make sense that your recently installed r2 cant find this symbol as libr_main links against libr_util.

capstone3 is SUPER OLD, not to say that capstone4 is also quite old and full of bugs and missing instructions. the only reason to keep support for such old versions of capstone is because they have been released and distros are packaging it. But if you care about using r2 or doing some reverse engineering outside a hello world crackme i would suggest you to build r2 with latest capstone from git which is what it does by default.

The error you are having doesnt seems related to capstone. i dont see why r2 would stop to run unless you have installed r2 from the ubuntu repositories. so i bet there are leftovers around and you still have ancient libs from r2 around

**Comment by diaevd** [comment]
There is no radare2 in the Ubuntu 22.10 repositories, it was transferred to snap a long time ago. But I don't want to use the snap package, I'm trying to build and run radar from the git repository. I'll try to figure it out myself. I don't believe in miracles.
The fact is that configure --without-capstone or configure --with-cap stone 4 do not give a result. libcapstone.3 is linked to the binary anyway.

**Comment by trufae** [comment]
Why do you have capstone3 and why it matters that much to link to it? Cant you just build with the capstone shipped with r2?

**Comment by diaevd** [comment]
```sh
diaevd@veles(master %|u= origin/master):~/src/Reverse/radare2/binr/radare2$ rg capstone
Makefile
86:LDFLAGS+=../../shlr/capstone/libcapstone.a
```
Shouldn't it be linked statically?

```sh
diaevd@veles(master %|u= origin/master):~/src/Reverse/radare2/binr/radare2$ ldd ./radare2
# ... skip ...
	libr_lang.so => /usr/local/lib/libr_lang.so (0x00007f5a62550000)
	libuv.so.1 => /lib/x86_64-linux-gnu/libuv.so.1 (0x00007f5a6251f000)
	libcapstone.so.4 => /lib/x86_64-linux-gnu/libcapstone.so.4 (0x00007f5a61ed2000
```
But it still links libcapstone dynamically.
I haven't figured out exactly what happened yet, but it still worked. 

```sh
diaevd@veles(master %|u= origin/master):~/src/Reverse/radare2$ r2 -v
radare2 5.7.7 28960 @ linux-x86-64 git.5.7.6-278-g1e57fabb3
commit: 1e57fabb3ecdfa6cda9165369cad439ee8e2c4c3 build: 2022-09-09__17:52:40
```
I will try to repeat all the steps step by step again to find out under what conditions it did not work.
