### ISSUE TITLE
WARN: Module version mismatch for asm_m32c_gnu.so (5.4.3) vs (5.8.1) and anal_m32c_gnu.so

### ISSUE THREAD

**Issue by cryptax** [radareorg/radare2#21263]
## Environment

I perform a fresh install of r2 from git with `radare2/sys/install.sh`. It seems to install correctly.

```
cd "/usr/local/lib/radare2/" && rm -f last && ln -fs 5.8.1 last
cd "/usr/local/share/radare2/" && rm -f last && ln -fs 5.8.1 last
mkdir -p "/usr/local/share/radare2/5.8.1/"
/bin/sh ./configure-plugins --rm-static //usr/local/lib/radare2/last/
configure-plugins: Loading ./plugins.cfg ..
Removed 0 shared plugins that are already static
```
## Description

When I run `r2 `, I get unexpected warnings:

```
$ r2 /bin/ls
WARN: Module version mismatch /home/axelle/.local/share/radare2/plugins/asm_m32c_gnu.so (5.4.3) vs (5.8.1)
WARN: Module version mismatch /home/axelle/.local/share/radare2/plugins/anal_m32c_gnu.so (5.4.3) vs (5.8.1)
WARN: run r2 with -e bin.cache=true to fix relocations in disassembly
```

Why do I get the 2 module mismatch? How can I remove the warnings?

**Comment by trufae** [comment]
That's expected. it means that the last time you build m32c was for r2-5.4.3, and r2 breaks the ABI on every minor version (this is 5.6, 5.7 and 5.8 had different ABIs. but 5.6.1 plugins can work fine with 5.6.7 builds of r2. the problem is that r2-5.8 completely removed the asm plugins. so you only need to build the anal one
