### ISSUE TITLE
r2 graph mode does not scrolls anymore

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#21765]
## Environment

```sh
$ r2 -v
radare2 5.8.7 30451 @ linux-x86-64
birth: git.5.8.6-75-g485eac300c 2023-05-22__15:12:49
commit: 485eac300c7609b577672c1522e3e0d57790669c
```

## Description

r2 graph mode does not scrolls anymore. When I use arrow key, r2 writes ^^[B instead of scrolling down.

**Comment by trufae** [comment]
Which terminal are you using? Because it works well for me

**Comment by trufae** [comment]
Bash is a shell not a terminal. You can use the standard hjkl too

**Comment by gogo2464** [comment]
I am using:

/usr/libexec/gnome-terminal-server

**Comment by gogo2464** [comment]
Both methods do not work.

**Comment by brzzh** [comment]
doesnt work for me too, same if using visual mode with panels or debugging something in visual, doesnt work in xfce4-terminal on linux or in mac with terminal, got broken sometime early this month imo

**Comment by radare** [comment]
i assume this https://github.com/radareorg/radare2/pull/21777 fixes your issue. but please next time explain the steps to reproduce because i always enter visual graph through the visual mode, not using the agv command from shell

**Comment by trufae** [comment]
How are you entering the graph mode? The issue happens because of an optimization i did two days ago. Thankd for testing it!

**Comment by Saikishore-Gowrishankar** [comment]
> How are you entering the graph mode? The issue happens because of an optimization i did two days ago. Thankd for testing it!

I start the program by doing "r2 -A <name of file>". Then I type "v" to enter the graph mode. Here, I try to scroll up or down. But instead of scrolling, it merely prints a bunch of characters like ^[[B or ^[[A numerous times on the screen, and doesn't scroll unless I hit the "ENTER" key, at which point all the times I have hit the arrow key is recognized in the program and it scrolls up however many times I hit the Up key before clicking Enter. 

I am testing it on Ubuntu 23.04 on the default terminal, but I used other terminals like Xterm and the same issue is there.

As an aside, after I open the r2 graph mode and I quit out of r2, my whole terminal also seems broken now and every time I hit a non-ascii character like the Up arrow or I click on the terminal screen somewhere, it outputs the keycode to the prompt. The terminal is broken like this until I close out of it and open a new instance

**Comment by trufae** [comment]
Then its an issue in panels mode. v is not the graph mode or the visual one. Ill fix and test that in few mins when i can reach my laptop again. Thanks for describing the steps!

**Comment by gogo2464** [comment]
it now works for me on the very latest PR!! 

thanks @radare

**Comment by brzzh** [comment]
can confirm, V! works again
➜  r2 -v       
radare2 5.8.7 30563 @ darwin-arm-64
birth: git.5.8.6-107-g4bc67cd02f 2023-05-25__09:45:55
commit: 4bc67cd02f8254ec1177f89201e1c7ab4776af4c
options: gpl -O2 cs:5 cl:2 make

**Comment by trufae** [comment]
Sweeet! Thanks for reporting :) i hope i squashed them all. I tried to reduce the amount of times the console was set to raw mode to speedup reading from console and this caused the problem

**Comment by trufae** [comment]
No need to reopen but give me the steps to repro. Ill review again all the code tonight maybe i missed a check somewhere

**Comment by gogo2464** [comment]
radare2 file;
s mysymbol;
af;
VVp;
p ; # to view opcode

**Comment by Erarnitox** [comment]
Hey, I know this is an old issue, but this might be helpful for someone searching for it in the future:

Can you try to "e scr.cursor=false" (you can also set this in your .radare2rc file). 

For me I had this issue when I enabled the cursor. I have tested it in different terminal emulators including: 
- kitty, 
- uxterm, 
- xterm 
- and coolretroterm. 

It can be reproduced in all of them, so I suspect this to be an issue on radares side when you have the cursor enabled.

However, maybe this behavior is even intentional? You are controlling the cursor now, not the seek with your inputs.

Just wanted to leave this here if someone searches for that online.

**Comment by gogo2464** [comment]
I suspect that a few terminal such as coolretroterm may create bug when it handles color.  Try: `e scr.color=false`, just to see.
