### ISSUE TITLE
r2 loads both slices of a fat mach-o binary when specifying 64 bit

### ISSUE THREAD

**Issue by Tyilo** [radareorg/radare2#2184]
Binary used (kextd): https://a.pomf.se/okgdhb

```
$ otool -f kextd
Fat headers
fat_magic 0xcafebabe
nfat_arch 2
architecture 0
    cputype 7
    cpusubtype 3
    capabilities 0x0
    offset 4096
    size 172976
    align 2^12 (4096)
architecture 1
    cputype 16777223
    cpusubtype 3
    capabilities 0x80
    offset 180224
    size 165952
    align 2^12 (4096)
$ r2 kextd
[0x0000243b]> / foo
Searching 3 bytes from 0x0000243b to 0x00022790: 66 6f 6f
#6 [0x243b-0x22790]
hits: 0
$ r2 -b 64 kextd
[0x100000c7a]> / foo
Searching 3 bytes from 0x0001a034 to 0x10001fdd8: 66 6f 6f
#6 [0x1a034-0x10001fdd8]
hits: 0
```

As you can see r2 searches from address `0x0001a034` to `0x10001fdd8` in the 64 bit slice, instead of starting from the mach-o header at `0x100000000`.

There is also some problems with the analyzer as `aa` doesn't seem to find all the used functions.

Shouldn't the 64 bit slice also be the default when I'm on a 64 bit system? It seems like it is for other binaries.

**Comment by radare** [comment]
the offsets seems to match with otool, so this doesnt seems to be a bug.

The problem you are pointing is not related to fatmach0, but related to the search method configured in search.in, by default it will find in the file contents. but this depends on the value of io.va, which in is set to true, it will only walk over the sections mapped. the address of the header is not mapped, so this results in a wrong range calculation. this doesnt happens on /bin/ls for example. because the address of some sections are too low on kextd. I guess the loader would rebase the vaddr of those sections, but i should try to understand what it will do.

In fact, when doing fatmach0, the io should create a new map at the specific range, and use the mach0 info from there, and then apply the sections on top of it.

yes. 64bit should be by default, so this is another bug. Maybe we shuold split this bug into some sub-bugs.

you can override the range of memory adding a new section that covers all the range, but i agree that this sohuld be something done by default. When working with fatbins you probably want to rabin2 -x to eXtract the sub-bins, and work directly with them

are you using r2 from git?

About the code analysis. ‘aa’ is not the only code analysis you can do, in fact there are several other commands and options to play with. when i want to do a full analysis, i usually run ‘ac’ too.

See all the `e anal.` options to enhace the finding of more functions, etc

**Comment by Tyilo** [comment]
> are you using r2 from git?

Yup the latest version from git

> About the code analysis. ‘aa’ is not the only code analysis you can do, in fact there are several other commands and options to play with. when i want to do a full analysis, i usually run ‘ac’ too.

Also using `ac` did the job for me, thanks.

**Comment by radare** [comment]
latest git removed the debug printfs :)
