### ISSUE TITLE
r2 segfaults when opening this SEP firmware

### ISSUE THREAD

**Issue by Siguza** [radareorg/radare2#22080]
## Environment

```sh
% date
Thu Jul 20 04:47:45 CEST 2023
% r2 -v
radare2 5.8.9 30978 @ darwin-arm-64
birth: git.5.8.8-321-g059fa3f0e3 2023-07-20__04:46:18
commit: 059fa3f0e3d4ad93ddafac11c29fdfa497f35ca5
options: gpl -O2 cs:5 cl:2 make
% uname -ms
Darwin arm64
```

## Description

File: [sepfw.gz](https://github.com/radareorg/radare2/files/12101654/sepfw.gz)

Command:
```
% gunzip sepfw.gz
% r2 -aarm -b64 sepfw
zsh: segmentation fault  r2 -aarm -b64 sepfw
```

Doesn't crash with `-n`, but I didn't investigate further.

**Comment by trufae** [comment]
Thanks for reporting! Sorry for the 5h delay for the fix i was sweat^Wsleeping :D 

Do you know if the SEP header has changed? because this seems like an invalid value for that field, i did a workaround to make it work even with invalid values in the header struct, but maybe worth having a look at the rest of unknown fields.

**Comment by Siguza** [comment]
The SEP header changes every now and then. I don't keep track of it, but I know that versions 14.4, 14.5, 15.0, 15.6, 16.0 and 17.0 betas all have different headers. Most of the time it's just one or two new fields in a struct, but in 16.x they even moved the string "Built by legion2" around.
