### ISSUE TITLE
Include refs on rcall and ucall on pdfj command

### ISSUE THREAD

**Issue by attilamester** [radareorg/radare2#22576]
## Description

* the whole story is described in this long (sorry) issue: https://github.com/radareorg/radare2/issues/22571#issuecomment-1933797133

* basically, including refs on `rcall` / `ucall` would save us form implementing a memory/register tracer

* is it planned?

**Comment by trufae** [comment]
The information is there, if you miss it just extend the command to include the missing info and I will evaluate it.

The computed / emulated references are registered with the aae command, so first of all iw ould suggest you to use latest r2 from git, and then try other commands like axj to get the registered xrefs instead of the ones from the graph command. but in any case i agree with you that those refs should be exposed.

Modifying the code should be just 1-2 lines as much. So I would encourage you to do such change to fit your needs.

**Comment by trufae** [comment]
Additionally it would be great if you can provide a reproducer in form of a test, i dont have the files you are using for testing and having it verified in the testsuite is always good to avoid brokenness at any time

**Comment by trufae** [comment]
commit from master recommended for wat?

**Comment by attilamester** [comment]
Commit from master which you consider stable.

**Comment by trufae** [comment]
Master is always stable

**Comment by attilamester** [comment]
## Update

* found out that with `e asm.emu=true`, `pdf` has the information I need in comment:
```
0x004062a1      8b3d38014300   mov edi, dword [sym.imp.KERNEL32.dll_HeapAlloc] ; [0x430138:4]=0x3020c reloc.KERNEL32.dll_HeapAlloc ; edi=0x3020c reloc.KERNEL32.dll_HeapAlloc
│           0x004062a7      6a20           push 0x20                   ; 32 ; esp=0xfffffff4
│           0x004062a9      6a08           push 8                      ; 8 ; esp=0xfffffff0
│           0x004062ab      ff3550024300   push dword [0x430250]       ; esp=0xffffffec
│           0x004062b1      ffd7           call edi                    ; esp=0xffffffe8 ; eip=0x3020c reloc.KERNEL32.dll_HeapAlloc
│                                                                      ; LPVOID HeapAlloc(-1, -1, ?)

```
* this is missing from `pdfj` -- there is no call to `ds_print_esil_anal_init` on commit 1ee768a40f569849fdb7d1114deac93700fcec80

**Comment by trufae** [comment]
The comments displayed as comments when emu.str=true (or asm.emu=true) are computed at disasm time, those are not recorded anywhere unless you perform a specific emulation analysis like `aaex` (but there are other commands that can perform this emulation and register the xrefs for the register calls).

Can you give it a try and see if that works for you?

**Comment by trufae** [comment]
you can use `?*~...` to find out other commands that may register refs with emulation. Also this string should be listed with `pdc` too

**Comment by trufae** [comment]
Can yiu provide a distributable sample or point to a binary to reproduce this? I can add a testcase for this and try different analysis methods to see which one works the best and maybe include it under aaas

**Comment by attilamester** [comment]
> you can use `?*~...` to find out other commands that may register refs with emulation. Also this string should be listed with `pdc` too

I tried `?*~...`, searched for `esil` and `emul`, there are indeed a bunch of possibilities, but still `pdfj` would be the best in my case. I have forked the repo and currently working on modifying **r_core_print_disasm_json** to include the functionality from **r_core_print_disasm**

> Can yiu provide a distributable sample or point to a binary to reproduce this? I can add a testcase for this and try different analysis methods to see which one works the best and maybe include it under aaaa

Yes, I am testing on this sample https://bazaar.abuse.ch/sample/c7cb8e453252a441522c91d7fccc5065387ce2e1e0e78950f54619eda435b11d/
Function 0x0040629f has 2 `call` instructions with register parameters (`call edi`)
I am trying to modify `r_core_print_disasm_json` such that `pdfj` includes `refs` on these two instructions.

**Comment by attilamester** [comment]
## Update

My work-in-progress can be seen on https://github.com/radareorg/radare2/compare/master...attilamester:radare2:feature/22576-pdfj-rcall

- copied some esil-related code from r_core_print_disasm to r_core_print_disasm_json
- since `ds_print_esil_anal` prints the esil info to stdout, used some ugly way of capturing its output into a buffer to add later to `pdfj`


Can you please have a look on this commit and give me hint/direction if this is the way to go? Thanks!

**Comment by trufae** [comment]
i had a lot of terrible events in my life recently so i couldnt check this out until now. do you have any updates here? can you submit a PR to make it easier fo rme to review? thanks! i think it looks good the way you do that. at the end you want the same info from pd into pdj, right? so you need to do linear emulation.

another approach that could be probably better would be to have an emulation analysis command (there are a bunch of them) but basically to use an anal hint to modify the instructions with the emulated details. this is better approach because it happens once instead of every time, and also performs the emulation recursively following the graph. 

This emulation can also register xrefs, and you should be able to see those xrefs in the current pdfj. but im not sure about that. So, to proceed here:

* make a PR with your changes
* add tests

i have a similar issue to resolve in a separate binary, so i;ll do that analysis step and come back to you to see if that fits your needs too.

thanks! and once again sorry for the delay. my life sucks these days

**Comment by attilamester** [comment]
Hi Trufae, I'm sorry to hear that - hope that you are doing fine.
You are right, I wanted the same info from pd into pdj, but I did not manage with the implementation, and found some workaround in my research to overcome this problem - basically, we ignore the dynamic/register calls for now.

If you guys have time to finish the implementation linked above, that is great for the community and future I think, unfortunately I will not have time to continue it, due to the paper deadline approaching. Thank you again.

**Comment by trufae** [comment]
I picked your changes into this rebased PR https://github.com/radareorg/radare2/pull/22763 and ill try to get it ready before the release. thanks for the effort

**Comment by trufae** [comment]
i think you want to use pdJ instead
