### ISSUE TITLE
implement handling of R_X86_64_TPOFF64 relocation

### ISSUE THREAD

**Issue by koyaan** [radareorg/radare2#22742]
## implement handling of R_X86_64_TPOFF64 relocation

This is "Offset in initial TLS block" relocation and newer libc have it apparently and we get a lot of spam resolving `main_arena` via relocations because this is not handled. 
 
Should go somewhere here  i guess https://github.com/radareorg/radare2/blob/180fea967b4f42ef91a4c31f5092c71989d086a1/libr/bin/p/bin_elf.inc.c#L533

more info:  https://chao-tic.github.io/blog/2018/12/25/tls

**Comment by koyaan** [comment]
@trufae  i will try to whip up a test binary tonight

**Comment by trufae** [comment]
Some random hints:

* This relocation type subtracts the thread pointer (usually %fs or %gs register in x86-64) from the symbol's offset within the TLS segment.
* There's also a 32 bit form of the same reloc:
* Sample instruction 'movl %fs:a@tpoff, %eax'
* In that case the instruction is encoded like this: 648b0425XXXXXXXX

We just need to save the absolute value of the reloc in the instruction + 4

the 64bit form of movl is movq, which is the same, but starting with 6448b0 instead of 64b0, and the offset is +5

in theory this offset+4 or offset+5 should be implicit by the reloc rva. but will be good to verify. so if all this theory is correct. that patch should be enough: can you try it out and update your "supress reloc warning" PR with the proper implementation? thank you!

```
diff --git a/libr/bin/p/bin_elf.inc.c b/libr/bin/p/bin_elf.inc.c
index 756eaa2db8..af2099533c 100644
--- a/libr/bin/p/bin_elf.inc.c
+++ b/libr/bin/p/bin_elf.inc.c
@@ -844,6 +844,11 @@ static void _patch_reloc(ELFOBJ *bo, ut16 e_machine, RIOBind *iob, RBinElfReloc
  			r_write_le32 (buf, v);
 			iob->overlay_write_at (iob->io, rel->rva, buf, 4);
 			}
+			break;
+		case R_X86_64_TPOFF32:
+			word = 4;
+			V = S + A;
+			break;
  		default:
  			break;
  		}
@@ -851,6 +856,10 @@ static void _patch_reloc(ELFOBJ *bo, ut16 e_machine, RIOBind *iob, RBinElfReloc
 	case EM_X86_64: {
 		int word = 0;
 		switch (rel->type) {
+		case R_X86_64_TPOFF64:
+			word = 4;
+			V = S + A;
+			break;
 		case R_X86_64_8:
 			word = 1;
 			V = S + A;

```

**Comment by koyaan** [comment]
added test binary https://github.com/radareorg/radare2-testbins/pull/96

**Comment by trufae** [comment]
in the CI we have this
<img width="435" alt="Screenshot 2024-03-26 at 20 17 15" src="https://github.com/radareorg/radare2/assets/6431515/674e6c6c-49ec-4a55-b7bb-74419590d03c">

**Comment by koyaan** [comment]
yeah those are from `reloc_convert` https://github.com/radareorg/radare2/blob/180fea967b4f42ef91a4c31f5092c71989d086a1/libr/bin/p/bin_elf.inc.c#L533 needs addition

**Comment by koyaan** [comment]
And if i understand this particular reloc can only be resolved after the loader has done its job since module load order is not guarenteed. The reloc then contains a negative offset from the static TCB

**Comment by trufae** [comment]
Having an offset starting from address 0 should be enough

**Comment by trufae** [comment]
I think fixing this is blocker for the release. Did you tried my patch? We should silence also the ones seen in the ci

**Comment by koyaan** [comment]
just tried to apply your patch, it wont compile
`/home/koyaan/code/r2heap/libr/..//libr/bin/p/bin_elf.inc.c:849:25: error: ‘word’ undeclared (first use in this function)`

**Comment by koyaan** [comment]
Your patch does not compile for me, could you do a PR?

**Comment by koyaan** [comment]
:+1:
