### ISSUE TITLE
http server: null headers break HTTP RFC

### ISSUE THREAD

**Issue by ElDavoo** [radareorg/radare2#22818]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
Wed 10 Apr 2024 10:33:48 AM UTC
radare2 5.9.1 31936 @ linux-x86-64
birth: git.5.9.0-46-g04f3d9d3e9 2024-04-09__13:51:30
commit: 04f3d9d3e99e8fdca10ba33c996d4eee2235b904
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

The HTTP server prints invalid HTTP headers for some files. Many softwares just ignore these headers, but some of them [do not](https://github.com/golang/go/issues/63168).

This happens because, in [r_socket_http_response](https://github.com/radareorg/radare2/blob/c9a9b63a3bd63aaf9d2c79de5df28e3e747996a2/libr/socket/socket_http_server.c#L121), `const char *headers` might be null, and thus when [r_socket_printf](https://github.com/radareorg/radare2/blob/c9a9b63a3bd63aaf9d2c79de5df28e3e747996a2/libr/socket/socket_http_server.c#L137) gets called, "(null)" will be printed in the middle of the response, breaking HTTP compliance.  

I guess that r_socket_printf needs to be fixed/expanded to just print nothing instead of "(null)".  

## Test

```
curl 127.0.0.1:8003/m/vendors/fonts/Roboto-normal-400.woff -v
*   Trying 127.0.0.1:8003...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8003 (#0)
> GET /m/vendors/fonts/Roboto-normal-400.woff HTTP/1.1
> Host: 127.0.0.1:8003
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 ok
< (null)Connection: close
< Content-Length: 20344
<
```

**Comment by trufae** [comment]
RSocket.printf uses vsnprintf which makes passing NULL to %s UB, because some systems like Solaris treat this as a segfault, the (null) thing is just a facility from the modern unixes. but afaik its not specified in the standard.

Before passing this NULL pointer as argument, this should be checked and convert it to "" instead. and actually the function (http_response) checks for null headers, the problem is that this (null) is constructed from the guess_mimetype which causes the function to return null.

i made a patch to fix all those issues and extended the list of known mimetypes.

thank you!

**Comment by ElDavoo** [comment]
Nice, congrats and thank you for the detailed analysis and quick resolution
