### ISSUE TITLE
r2 in visual mode blocks when steping over a call to a function that read from stdin

### ISSUE THREAD

**Issue by imenyoo2** [radareorg/radare2#23262]
## Environment

```sh
Sat Aug 31 04:55:10 PM EDT 2024
radare2 5.9.5 32482 @ linux-x86-64
birth: git.5.9.4-86-ge3687f0905 2024-08-31__12:07:03
commit: e3687f0905a1be6a561f414672485ff725d8db26
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

when steping over a call to a function that read from stdin, visual mode blocks and it seems like there is no way to exit, idk if this is intended or not

## Test

```
;-- eip:
0x08048734      e817fdffff     call sym.imp.fgets
```
in visual mode, when clicking `S` here to step over this instruction, it blocks

**Comment by trufae** [comment]
Thats totally expected and desirable.

**Comment by imenyoo2** [comment]
but i had to kill the process each time that happen, am i doing something wrong here ?

**Comment by trufae** [comment]
the child process waits for input from stdin. Just please him with some chars and a newline and the debugger will continue. If you are debugging in visual the same process in the same terminal then you may have problems because visual mode puta the terminal in raw and also processes events from the same file descriptor. Just debug from the shell or spawn the process in a separate terminal
