### ISSUE TITLE
How to debug a shared library?

### ISSUE THREAD

**Issue by fduxiao** [radareorg/radare2#23433]
I have a program `a`, which depends on `libb.so`, which depends on `libc.so`. Now, I want to debug `libc.so` by running `a`. How can I do that?

I tried loading `libc.so` first and running command `aaa` and `doof a with some args`. But, r2 tells me it cannot work on an outside file.

**Comment by trufae** [comment]
if you are debugging a program that depends on a library, this library is loaded in memory, therfor you are debugging it too. if you want to debug the library itself without the program, like windows users do with rundll you can do this with rarun2.

I guess what you want is to load all the symbols from the library, for this you have to use the `dmi` command. its not loaded by default because of performance reasons. so we prefer to load just the minimum stuff instead of loading all the symbols from all the libraries unless the user asks for it using this command. hope that helps
