### ISSUE TITLE
Problem displaying stack variables

### ISSUE THREAD

**Issue by rolio37** [radareorg/radare2#23505]
## Environment

$ r2 -v
WARN: Duplicated register definition for 'rflags' has been ignored
radare2 5.9.7 32743 @ freebsd-x86-64
birth: git.5.9.6-37-gf85d1bc1d1 2024-10-18__22:27:11
commit: f85d1bc1d1fd4a224242d0226211ce303a20ee4c
options: gpl -O? cs:5 cl:2 make
$ uname -ms
FreeBSD amd64

## Description

Stack variable not showing on ucomisd instruction.
The stack variable is displayed correctly in the instruction:
0x00201757      f20f1145f0     movsd qword [var_10h], xmm0
But it does not display the stack variable var_10h in the instruction:
0x0020178f      660f2e45f0     ucomisd xmm0, qword [rbp - 0x10]
The instruction should be:
0x0020178f      660f2e45f0     ucomisd xmm0, qword [var_10h]

## Test

Program test :
https://github.com/rolio37/re/blob/main/crackme_xmm.c

![xmm](https://github.com/user-attachments/assets/c9215410-ca42-412a-a9b5-40a6dd50aa9a)

**Comment by rolio37** [comment]
In which file should I look for the problem ?

**Comment by trufae** [comment]
the whole stack analysis needs a lot of attention, didnt spent much time on it. the code you are looking for is in different places. the variables are defined by core/canal.c around line 5360. just grep for r_anal_function_set_var to see where the vars are created. but the problem is probably related to the arch plugin not exposing the proper metadata in the RAnalOp for MMX instructions. see libr/arch/p/x86/plugin_cs.c and grep for the ucomisd instruction

**Comment by rolio37** [comment]
Ok thanks for the information to find the problem. 
I don't know if it's within my capabilities. 
I'll try...

**Comment by rolio37** [comment]
Problem solved :)
