### ISSUE TITLE
Wrong analysis while debugging with e dbg.profile

### ISSUE THREAD

**Issue by alvarofe** [radareorg/radare2#3005]
The binary is 
![vortex3](https://cloud.githubusercontent.com/assets/3474042/8889836/1ed78246-32eb-11e5-900f-9b41856c97c3.png)

Here the issue [asciinema](https://asciinema.org/a/8o00jutz7zb470gxp60sgszha)

Laptop

```
[alvaro @ ctf] $ uname -a
Linux void 4.1.3_1 #1 SMP PREEMPT Wed Jul 22 06:07:23 UTC 2015 x86_64 GNU/Linux
```

**Comment by radare** [comment]
You are doing it wrong

When starting the process with a profile you have to continue until entrypoint. Because at the start point you are in the ld.so, so the bin is not yet fully loaded, and when you are using rarun2, the program have a prepararion to run and setup the environment and as long as the default entrypoint is the loader you cant expect to have the target binary loaded yet.

Use dbg.bep=entry0, or just dcu entry0. That should work.

**Comment by alvarofe** [comment]
But that doesn't happen with other example. The difference between the binaries is that strcpy was replaced by gets.

http://asciinema.org/a/bsxf5ufkrc7p9uqkyywjmtp2c

and doing what you told me doesn't work.

I think that the issue is related with `arg1=!python vortex3.py`
