### ISSUE TITLE
Add the ability to name debugmaps by the user

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#3380]
in osx, or kernel debugging not all memory maps contain a meaningful name, but it can be deduced with manual interaction,so it would be helpful to add comments to the debugmaps (bear in mind that debugmaps are reloaded, so this info should be stored somewhere else and merged on every sync)

**Comment by trufae** [comment]
I have though about this issue and i dont see much benefit on having this feature for the following reasons:

* maps cant be renamed (they take the filename), there are no apis for that
* local renaming is just useless because restarting the process will loose that info
* this info wont be saved in projects so its useless
* we have flags and comments to do the same

**Comment by trufae** [comment]
Eventually we can show the flag or comment that is found in the starting address of each map in the output of dm
