### ISSUE TITLE
Can't build out of source dir

### ISSUE THREAD

**Issue by davispuh** [radareorg/radare2#3636]
Seems currently it's not possible to build outside of source directory. 
It's very useful because you can easily just `rm -rf build` dir and leaving source dir unaffected by build.

**Comment by jjdredd** [comment]
do you want cmake?

**Comment by davispuh** [comment]
CMake would be great and for it's very simply to build out of source dir but that's not really requirement for out of source dir building, just need so build scripts don't assume current directory is source dir.

**Comment by jjdredd** [comment]
so you want to add a ${BUILD_DIR} to every -o option of gcc?

**Comment by radare** [comment]
there’s some gmake magic behind the VPATH variable, but it turned to be dark magic so i droppoed it, i dont really see any benefit in compiling out of source directory, but any PR will be welcome

**Comment by davispuh** [comment]
> so you want to add a ${BUILD_DIR} to every -o option of gcc?

Not really, it works other way, like
```bash
cd $build
$srcdir/configure
make
make install
```

It's configure responsibility to create makefile in current dir which references source dir. But here makefile isn't generated in current directory even when configure succeeds without errors.

Anyway it's not really big deal and I don't really know anything about Autotools.
I find it preferable because of source code and build result separation, it's especially useful if you want to cross-compile for multiple architectures then you've just different build dirs.

**Comment by jjdredd** [comment]
Are you proposing autotools?

**Comment by davispuh** [comment]
@jjdredd are you retarded? You just keep asking questions and they don't really make any sense as I already said what I wanted and no I never claimed that, but radare uses acr which is almost as same as autotools.

**Comment by jjdredd** [comment]
@davispuh Is that the way you usually talk to people? I suggest you change your tone.

**Comment by davispuh** [comment]
@jjdredd I suggest you to GTFO as you don't add anything to this issue and your questions don't lead us anywhere to solve this issue. Anyway I've already said everything so I'm not commenting here anymore.

**Comment by trufae** [comment]
![](http://i.ytimg.com/vi/JRZGTnjCLOo/hqdefault.jpg)

**Comment by radare** [comment]
Keep calm dudes. I use to be rude, but just in words. But i understand this can offend someone at some point. I don't want r2land to be an offensive place.

@davispuh please, take a break before replying in that way. acr emulates autoconf, but absolutely not the same as autotools, there's no automake process involved (which would be the solution for this problem), but it will also make configure stage much more bloated, in the way that it will need to create a lot more makefiles. also, acr is infinitely smaller and faster than autotools. I wouldn't switch to autotools. and I also dislike cmake for different reasons. Do you have any suggestion about using VPATH or mixed crosspath makes and original makefiles? this will solve the problem of replicating the entire mk environment into a subdirectory

@jjdredd I dislike cmake and autotools. I have experimented with waf, bjam and other build systems, and i'm still stuck at make because I think is the only true build system out there. The problem of supporting crosspath builds is that it requires to create new makefiles everywhere which will make our build system even more complex. I have some plans after 1.0 to solve all this stuff, but i dont think we can have a proper rewrite.

Another interesting build system for r2 will be to support VS, it will make life easier to windows contributors because, crosspath builds is not the only problem we have in the current build system.

**Comment by ret2libc** [comment]
This can be closed. We have `meson` now at it easily supports out-of-source builds :)
