### ISSUE TITLE
Kill SEEK command from RAP protocol

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#4172]
Maybe we should mimic the siol branch design
- kill seek
- put offset parameter on read and write ops
- add getsize callback

**Comment by trufae** [comment]
I don't see any benefit in removing a command to add another one (and removing the ability to do sequantial reads and breaking backward compat with the RAP protocol) is not the good change. Another reason for not accepting this is because imho the RAP protocol is just another layer for IO, and it should be compatible with the way IO works.

Closing it now, unless @condret or @ret2libc have any words on it

**Comment by condret** [comment]
do. io effectively fakes seek, and only uses write_at/read_at and does seeking in the plugins below
