### ISSUE TITLE
Bankswitches?

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#448]
How can i perform bankswitches in anal_gb?
Each bank is sized to 0x4000.
rombank0 is fixed.
Depending on the MBC, defined in the gb-header, several write operations to ro-memory cause a bankswitch at (in most cases) 0x4000.
I'm fearing to confuse the reflines, if I just redefine the rva of a rombank-section.

How could I handle rambank-switches?

This all might be neccessary for tracing data

**Comment by ricardoquesada** [comment]
I also need bank support for disassembling c64 snapshots.
Was "bank support" added ? or is there any work around ?

Basically, I have 2 blocks of code, both of them must be mapped at the same address, but only one can be active.

**Comment by radare** [comment]
Ask @condret for this. This is similar to gameboy requirements. And i think this is done by changing priorities in the sections

**Comment by animaone** [comment]
It is done by changing priorities in sections? Can someone please explain this? And how this can be done? there is a tutorial somewhere?
I think rombank switching is a so specific thing that it should be implemented independently for each architecture.
I had to build my own disassembler because of this.
Maybe having a mechanism for switching the rombanks like the processor does? The software also will have specific inter-rombank calls which will be different for every software... so...

radare could offer a rombank switch, like a command to change rombank, maybe
if the processor can understand everything, the disassembler also can understand it,
most banks also will refer to functions in the bank itself, so, rombank switching should maintain everything working
without the section add/priority mess
