### ISSUE TITLE
MSVC demangling error

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#5446]
Try this 

```
"iD msvc ?AV?$Module@$00VInProcModule@Details@Platform@@@WRL@Microsoft@@"
```

It simply return nothing.

**Comment by oddcoder** [comment]
microsoft VC demangler fialed to demangle it I am worried that the name is faulty?
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin>undname.exe "?AV?$Module@$00VInProcModule@Details@Platform@@@WRL@Microsoft@@"
Microsoft (R) C++ Name Undecorator
Copyright (C) Microsoft Corporation. All rights reserved.

Undecoration of :- "?AV?$Module@$00VInProcModule@Details@Platform@@@WRL@Microsoft@@"
is :- "?AV?$Module@$00VInProcModule@Details@Platform@@@WRL@Microsoft@@"
```

**Comment by radare** [comment]
try demangling with an older version of r2 (0.10.4?)

**Comment by oddcoder** [comment]
didn't work too but I will find my way out

**Comment by XVilka** [comment]
No, it's known that VC demangler can't demangle it (yet), but it's produced by MSVC2015 and still valid.

**Comment by oddcoder** [comment]
it is broken before 0.10.4

**Comment by XVilka** [comment]
@xarkes may be you can check this closer to the end of summer, if you'll have time.

**Comment by riverar** [comment]
It's a RTTI type descriptor name, that describes the class (`.?AV[. . .]`) `Microsoft::WRL::Module<1,Platform::Details::InProcModule>`

**Comment by thestr4ng3r** [comment]
It works with the following (also note the .):
```
e anal.cpp.abi=msvc
"avrD .?AV?$Module@$00VInProcModule@Details@Platform@@@WRL@Microsoft@@"
```
The template arguments are not demangled correctly, but that could easily be implemented.

@riverar Since you recognized it's a type descriptor name, do you know of any sources that document the mangling in RTTI? I implemented `avrD` just from looking at examples and the regular symbol mangling, but I wasn't able to find any specific info on the internet about it. Especially what the `AV` (which is also `AU` in some cases) means.

**Comment by XVilka** [comment]
@GustavoLCR can you please check also this one?
