### ISSUE TITLE
Option to drop zeros from compiled instructions in nz assembler

### ISSUE THREAD

**Issue by Svenito** [radareorg/radare2#5816]
Some instructions have trailing zeros and nz should be able to drop these like olly does using the `SHORT` keyword

**Comment by radare** [comment]
nopes its not about trailing zeros, its about zeros at any place. the thing is that some places where you can put code doesnt allows to have some chars because they are invalid, so the idea behind this is to avoid those characters in the construction without using an encoder. just placing that inside the assembler would be enough, so in case we dont want zeros and we add 3 to eax, we can do the same in negative like: sub eax, -3. this way the resulting bytes will have no zeros.

**Comment by Svenito** [comment]
i see. Ok, that makes sense, but I'll need to do some reading up on this. Thanks for elaborating

**Comment by Svenito** [comment]
I'm not sure how to enable this behaviour for olly. It will always spit out opcodes with 0s for the above instructions.

**Comment by radare** [comment]
this is completely low prio. until we have no stable assemblers there's no much sense in adding this magic :) also another option that would be cool is to remove all non-printablechars, etc

**Comment by ret2libc** [comment]
Closing, given what said in https://github.com/radareorg/radare2/issues/5816#issuecomment-259749983 . However, please feel free to send a PR with the suggested changes and we'll be happy to review and merge them! Thanks.
