### ISSUE TITLE
esil not handling exit interrupt 

### ISSUE THREAD

**Issue by Svenito** [radareorg/radare2#6269]
using `aae` ignores exit interrupts and continues execution.

To reproduce
-----------------

Binary:
https://github.com/radare/radare2-regressions/blob/master/bins/elf/analysis/x86-helloworld-phdr

```
r2 x86-helloworld-phdr
aeip
Vp
```

step to end of function and beyond.

This causes `aae` to carry on and start executing instructions elsewhere, leading to errors. 

The function should also be marked as no-return.

**Comment by condret** [comment]
esil does not support this interrupt. there are almost no platformspecific interrupt handlers atm

**Comment by Svenito** [comment]
I assume that means they could be added then? I kind of implied that they might be added in the future.

**Comment by condret** [comment]
yeah, if i remember correctly you can do this by registering interrupthandlers in the corresponding anal-plugin. I once did an implementation for int 0x80, for testing purposes

**Comment by Svenito** [comment]
K, maybe I'll take a look at it when I have some time. I only discovered it as I was testing some other esil stuff

**Comment by radare** [comment]
yes.. it turned to be a vulnerability so i commented out the code..

**Comment by condret** [comment]
what vuln?

**Comment by radare** [comment]
you where not filtering the access to filedescriptors

so it was possible to read or write on ANY real file descriptor

opened by r2

the thing is that running -AA runs aae

which emulated the whole program to analyze code

the problem is that the crackme was correctly emulated, so instead of analyzing it... it was showing the prompt asking for password

like if it was executed

i was a bit wtf because it was a linux elf bin on osx :P

i think we should emulate some syscalls, but supported across all systems and archs. and having some proper security boundaries defined

**Comment by Maijin** [comment]
Ah yes that was awesome btw x)
