### ISSUE TITLE
Create tests and verify behaviour for SAR SARX, SHL, SHLR, ...

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#7367]
for x86, with positive and negative values..

should be almost fixed after 51aaf24dc11e42a4b19cd4e8641535cf5618e56b 

cc @Maijin 

test program:

```
main() {
        asm("mov $-8, %rax\nsarq $1, %rax");
        asm("sarq $1, %rax");
        asm("sarq $1, %rax");
        asm("sarq $1, %rax");
        asm("mov $-8, %rax\nshrq $1, %rax");
        asm("shrq $1, %rax");
        asm("shrq $1, %rax");
        asm("shrq $1, %rax");
}
```

**Comment by XVilka** [comment]
Related to https://github.com/radare/radare2-regressions/issues/808

**Comment by ret2libc** [comment]
I'm closing this. Yeah, we need tests for X, Y and Z, but we can't have a bug for each one of those things opened for years. Also, maybe instead of having manual tests for each thing, we should think about some more automatic way of doing tests: for example, when I worked on McSema they tested whether their lifting was accurate by doing something like:

1. dump CPU state as computed by X (esil in our case)
2. execute instructions in X (esil)
3. dump CPU state as computed by X (esil)

then

4. dump CPU state as computed by Pin
5. execute instructions in Pin
6. dump CPU state as computed by Pin

7. Compare state obtained at step 3. and 6. 

Something like the thing above, IMO, would be much more reliable than having manual tests for each instruction. It would be much easier to extend tests, etc.

**Comment by XVilka** [comment]
It's precisely what was done in https://github.com/sushant94/esil-tests

**Comment by ret2libc** [comment]
> It's precisely what was done in https://github.com/sushant94/esil-tests

Is it still maintained? As a result of that, were tests added to r2r to check all those instructions?
