### ISSUE TITLE
Load data types/structs from DWARF

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#741]
Load data types (both simple and complex) from DWARF and loading them into the sdb cparse storage for using with analysis engine

**Comment by radare** [comment]
related to the r2k cc @P4N74

**Comment by radare** [comment]
cc @jpenalbae

**Comment by radare** [comment]
any chance for this?

**Comment by P4N74** [comment]
we can use dwarf plugin for this purpose (that would need some more code since currently it extracts only structures and unions. But loading types for function variables would be easy). Only problem with that is the dependency on libdwarf. I don't know how r2 currently reads dwarf information. If r2 has its own code, then we might have to rewrite plugin.

**Comment by radare** [comment]
Its ok as a 3rd party plugin as its now
