### ISSUE TITLE
Gameboy analysis adds "sticky" comments that cannot be removed

### ISSUE THREAD

**Issue by JarrettBillingsley** [radareorg/radare2#7728]
This is with the git version of r2 (as of last night) and a clean install.

In this file: https://github.com/radare/radare2/blob/921cece22c106fdfa9939a31887845aec083741f/libr/anal/p/anal_gb.c

There are calls to `meta_gb_bankswitch_cmt` and `meta_gb_hardware_cmt` to add helpful comments on memory accesses to these memory mapped IO registers. They're great! But unfortunately, it's impossible to change or remove these comments.

Just to test, I commented out the calls to these functions, and now I can remove those comments from my project.

I don't know enough about the internals of r2 to know why `gb_anop` is being called repeatedly, or what is the right way to insert these comments while still allowing the user to remove them. 

Pinging @condret since they seem to be the gameboy expert here..

**Comment by JarrettBillingsley** [comment]
(Also the `r_meta_set_string` in that file for the "unpredictable", same issue)

**Comment by radare** [comment]
cc @condret

**Comment by manuelprinz** [comment]
Picking up on this old issue, as I made it worse with my latest changes. :wink: I also find the current solution less that ideal. The comments help, but the stickiness is kind of annoying. So I was thinking about the following: Instead of printing the address in hex and adding the comment, we could directly print the register mnemonics instead of the address. This is how it is used when writing assembly anyway. So instruction `e040` would become `ld [rLCDC], a` instead of `ld [0xff40], a`. We could drop the comments then, as this is fairly readable by someone who is (somewhat) familiar with GB assembly. For unknown registers, we could either display the number notation (e.g. `ld [rNR5], a`) or make the argument stand out more by using the offset, e.g. `ld [0xff00+5], a`.

Thoughts?

P.S.:  I would be willing to implement it.

**Comment by JarrettBillingsley** [comment]
That seems way better, tbh, cause I'd probably just go through and change them all to those register names anyway...

**Comment by manuelprinz** [comment]
That was quick! Let's go for this solution, then.

**Comment by condret** [comment]
sorry, I didn't see this. The thing about these sticky comments is, that they deserve their own kind of comment-space.
