### ISSUE TITLE
Virtual address issue while opening another file

### ISSUE THREAD

**Issue by xarkes** [radareorg/radare2#7913]
Example: `r2 -c "o whatever.exe" -`
The binary will be mapped to a different address unlike when you open it directly.
```
$ r2 bin.jpg
[0x00411055]>
^D
$ r2 -
[0x00000000]> o bin.jpg
6
[0x00011055]>
^D
```

**Comment by radare** [comment]
If you want to open r2 without any file use double dash --.

And you can open the other file in a different address, and swith between files opened to priorize the descriptors.

Also theres all the magic of sections and maps so you can also use them to avoid the overlapping. What you are expressing is not an issue. Its expected behaviour, so learn how to use sections, maps, fds and how to apply the va mode. Because you can control the mapped address, the base address and the virtual addresses of everything

**Comment by xarkes** [comment]
ack, was just surprised that when I have no file opened it's not mapped at the same address.

**Comment by radare** [comment]
Oh wait reopen. Pls i bet its assuming baddr =0 instead of -1

**Comment by xarkes** [comment]
Even though the seek address is not properly changed, it seems that the loaded binary with `o` is fixed now. i'm closing.
