### ISSUE TITLE
Disable need of io.va=0 for dalvik (enable by default)

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#8373]
Disable need of io.va=0 for Dalvik, this sounds a bit tricky for users :/ Especially if this a common behavior for all dalvik, should be by default.

CC @alvarofe 

https://github.com/radare/radare2-regressions/commit/9224ccf2c5ff225c4162ec0ab0e63f9761719f79

**Comment by radare** [comment]
Why that? Dalvik should and must work fine with iova=1

**Comment by alvarofe** [comment]
i~va is false, DEX does not have virtual address just looking at his section since va=pa and some sections get wrong his size and hence is not fully mapped. @h4ng3r should know better

**Comment by radare** [comment]
dex must be iova=1 because we want to load more than one dex at the same time for multidex, and ioav=0 only allows to read 1 file

**Comment by h4ng3r** [comment]
maybe this is a good topic for the hackathon... multidex cant be a patch or something custom, we need an standard way to handle multibin.

**Comment by alvarofe** [comment]
If io.va=1 then sections should be correctly created in rbin side cause now they have holes in virtual address space. I would just create one section with the whole file for dex and use rbin sections for analysis if they are needed. With that io.va=1 can be turned on again in DEX

About multibin is possible now with SIOL but rbin should be changed to make this easier so that should be the next target after io

**Comment by h4ng3r** [comment]
lgtm, thanks alvaro.

**Comment by condret** [comment]
not sure if I understand the problem correctly, but if we follow the earlier concept that every file needs a map, the result in va=0 and va=1 should be the same, as long as no other map gets created above

**Comment by radare** [comment]
agree on that

**Comment by alvarofe** [comment]
and it does work condret. The problem here is that rbin's section are not created correclty since va has holes when it shouldn't (actually DEX with io.va=1 would read in some places 0xfff cause there is nothing mapped). So to workaround that is the creation of a section that maps the whole file and left the others for just rbin and no mess around with io. I would do it today and update the tests

**Comment by h4ng3r** [comment]
I dont feel confortable with fixes and patches, maybe we should fix the hole issue.

**Comment by alvarofe** [comment]
dex is all yours, the size of the sections created are wrong like this

``` 
[00:00] . pa=0x00000000 mr-- va=0x00000000 sz=0x0070 vsz=0x0070 header
[00:01] . pa=0x00000070 mr-- va=0x00000070 sz=0x0134 vsz=0x0134 constpool
[00:02] . pa=0x000001a4 mr-x va=0x000001a4 sz=0x0044 vsz=0x0044 code
[00:03] . pa=0x00000342 mr-- va=0x00000342 sz=0x00a6 vsz=0x00a6 data
----
 2 fd: 3 +0x000001a4 0x000001a4 - 0x000001e7 -r-x fmap.code
 1 fd: 3 +0x00000342 0x00000342 - 0x000003e7 -r-- fmap.data
```
from 0x1e8 to 0x342 would be full of 0xff. Right know it does work with io.va=1 cause fallbacks to paddr, because of the map created for the desc, after I changed some stuff. But if the plugins return has_va to true, it will contain holes and analysis will fail

**Comment by ret2libc** [comment]
@trufae IMHO this can be closed. It seems to me the test mentioned in the first comment works as well with io.va=true.

**Comment by trufae** [comment]
Yep, the recent improvements on the sections and segments definitions in RBin.dex fixed this. And ther's even a test for this. closing
